### ISSUE TITLE
Persist data & recreate container -> Where is configuration stored after setup?

### ISSUE THREAD

**Issue by jkaa** [invoiceninja/dockerfiles#11]
According to dockerfiles comment:
> make your data persistant, you have to mount /var/www/app/public/logo and /var/www/app/storage.

- I did as proposed by mounting host directories and stepped through the setup process in browser
- afterwards I logged in and made some changes
- I stopped the containers, removed them and recreated them with `docker-compose up`

**RESULT:** 
The is no data in the host mounted folders AND I get redirected to the setup page over and over again (can not complete it a second time, I guess due to mysql already being initialized) without any errors.

**GOAL:**
I want to move the invoiceninja data folders and mysql folders around or even onto a different machine and fire up all needed services via `docker-compose up -d`, providing the variable for the host mount folder.

I really appreciate your help.

**Comment by lalop** [comment]
Hello,
can you share your docker-compose file ?

**Comment by lalop** [comment]
But to answer, the configuration is stored in the database

**Comment by lalop** [comment]
@jkaa did this answer to your question ?

**Comment by codedge** [comment]
Seems to be solved or outdated? Can we close the issue?

**Comment by jcoetzee** [comment]
Sorry to hijack this thread but playing with Invoice Ninja on docker I don't understand how this could work without mounting /var/lib/mysql in order to persist DB data? How else could DB data be persisted?

**Comment by jkaa** [comment]
I am a bit in a hurry:

- sadly this did not answer my question
- in the snippet below you can find the solution that worked for me. Please note lines commented out refer to my initial strategy to address the problem described in the issue, which did not work (different folders got mapped, ).
- in the web and app container are volumes_from directives pointing to the declared kind of 'volume containers'

```
    # container to fix directory permissions
    app-data:
       image: invoiceninja/invoiceninja
       container_name: ininja-app-data-permission-fix
       volumes:
#         - ${NINJA_FOLDER}/app/logo:/var/www/app/public/logo
#         - ${NINJA_FOLDER}/app/storage:/var/www/app/storage
          - data-ininja-app:/var/www/app
       entrypoint: /bin/bash -c "/bin/chown -R www-data /var/www/app"

    # container to fix directory permissions
    mysql-data:
       image: mysql
       container_name: ininja-mysql-data-permission-fix
       volumes:
          - data-mysql:/var/lib/mysql
#         - ${NINJA_FOLDER}/db/mysql:/var/lib/mysql
       entrypoint: /bin/bash -c "/bin/chown -R mysql:mysql /var/lib/mysql" 

volumes:
    data-ininja-app:
    data-mysql:
```
