### ISSUE TITLE
add a stack file for docker swarm

### ISSUE THREAD

**Issue by dottgonzo** [invoiceninja/dockerfiles#115]
Hi,

this is the first time i test this app.

My favourite orchestrator flavour is docker swarm, so i try to convert the compose file into a stack file.

Starting with the basic "usage" on the README.md file (right on this repo), i see:
```
docker run -d \
  -e APP_ENV='production' \
  -e APP_DEBUG=0 \
  -e APP_URL='http://ninja.dev' \
  -e APP_KEY='SomeRandomStringSomeRandomString' \
  -e APP_CIPHER='AES-256-CBC' \
  -e DB_TYPE='mysql' \
  -e DB_STRICT='false' \
  -e DB_HOST='localhost' \
  -e DB_DATABASE='ninja' \
  -e DB_USERNAME='ninja' \
  -e DB_PASSWORD='ninja' \
  -p '80:80' \
  invoiceninja/invoiceninja
```

so i has converted it as stack file:

```
version: '3.3'

networks:
  traefik-net:
    external: true
  mysql:
    external: true

volumes:
  invoice-ninja-logo:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/HC_Volume_3487555/invoiceninja/logo'
  invoice-ninja-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/HC_Volume_3487555/invoiceninja/storage'

  invoiceninja:
    image: invoiceninja/invoiceninja
    environment:
      APP_ENV: production
      APP_DEBUG: 0
      APP_URL: https://XXXXXXXX
      APP_CIPHER: AES-256-CBC
      DB_TYPE: mysql
      DB_STRICT: 'false'

      DB_HOST: mysql0
      DB_DATABASE: invoiceninja
      DB_USERNAME: invoiceninja
      DB_PASSWORD: XXXXXXXX
    networks:
      traefik-net:
      mysql:
    volumes: 
      - invoice-ninja-storage:/var/www/app/storage
      - invoice-ninja-logo:/var/www/app/public/logo
    deploy:
      placement:
        constraints:
          - node.labels.ninjavolume == true
      mode: replicated
      endpoint_mode: dnsrr
      labels:
        - traefik.port=80
        - "traefik.frontend.rule=Host:XXXXXXXX"
        - traefik.docker.network=traefik-net
        - traefik.frontend.headers.SSLRedirect=true
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 0
        window: 10s
```
(here i'm using traefik as proxy, but only as transparent proxy to resolve the app url)
it simply not works.

Then i was noticed that on the compose file you had configured nginx and share some folder with it. To share folder between containers is not my favorite choice, it is required? 

I'm thinking to point my proxy to 2 containers:
- an nginx app that serve static website 
- a php image for the backend
maybe by 2 different images (from same sources)

could be a good solution?
