### ISSUE TITLE
[Feature Request] Improve security by using docker secrets

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#125]
Please support "docker secrets" for passwords, API, keys, secrets, etc. Most major apps (and all databases) support this.

So instead of this:
````yml
version: "3.7"
services:

  mariadb:
    environment:
      MYSQL_PASSWORD: foo
    # ...etc.

  invoiceninja:
    environment:
      DB_PASSWORD: foo
      APP_KEY: bar
      MAIL_PASSWORD: baz
    # ...etc.
````

We can do this:
````yml
version: "3.7"
services:

  mariadb:
    secrets:
      - mariadb_password
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/invoiceninja_mariadb_password     # supported
    # ...etc.

  invoiceninja:
    secrets:
      - mariadb_password
      - app_key
      - mail_password
    environment:
      DB_PASSWORD_FILE: /run/secrets/invoiceninja_mariadb_password     # unsupported
      APP_KEY_FILE: /run/secrets/invoiceninja_app_key                  # unsupported
      MAIL_PASSWORD_FILE: /run/secrets/invoiceninja_mail_password      # unsupported
    # ...etc.

  secrets:
    mariadb_password:
      file: .invoiceninja_mariadb_password
    app_key:
      file: .invoiceninja_app_key
    mail_password:
      file: .invoiceninja_mail_password
````

This is more secure. Most secure database deployments do it like this, so invoiceninja is the weak link in the chain (as we need to put the password in plaintext).

Here are [the docs](https://docs.docker.com/compose/compose-file/#secrets-configuration-reference).
