### ISSUE TITLE
using SSL with docker-compose

### ISSUE THREAD

**Issue by peterwilli** [invoiceninja/dockerfiles#14]
Hi there,

I've made my docker-compose like this (I already have a SQL server running, hence the environment variables):

```yml
app:
  image: invoiceninja/invoiceninja
  environment:
    - DB_USERNAME=root
    - DB_PASSWORD=legaal

web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
  ports:
    - 9292:80
```

And then run another nginx instance outside docker that has the SSL configuration:

```
# HTTP
server {
    server_name xxx;
    # redirect non-SSL to SSL
    location / {
        rewrite     ^ https://$server_name$request_uri? permanent;
    }
}

# HTTPS server
server {
    listen 443 ssl spdy; # we enable SPDY here
    server_name xxx;

    ssl_certificate     /etc/webmin/xxx.pem;
    ssl_certificate_key /etc/webmin/xxx.pem;

    location / {
        proxy_pass http://127.0.0.1:9292;
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
```

The site shows up but the server still serves some resources as http, as we can see in this screenshot:
![screenshot from 2016-08-23 09-47-29](https://cloud.githubusercontent.com/assets/1212814/17884129/c8904c20-6916-11e6-81ef-e12a815aeafd.png)

**Comment by lalop** [comment]
can you try to set the APP_URL env var with https ?

**Comment by peterwilli** [comment]
@lalop nothing unfortunately :(

I tried like this (both with https and https://domain.xx):
````
app:
  image: invoiceninja/invoiceninja
  environment:
    - DB_USERNAME=root
    - DB_PASSWORD=legaal
    - APP_URL=https
```
