### ISSUE TITLE
Connection reset after deployment

### ISSUE THREAD

**Issue by SelfhostedPro** [invoiceninja/dockerfiles#163]
Here is my docker compose. I'm using this with an app template so all of the ${} variables are pulled from there. (https://github.com/SelfhostedPro/selfhosted_templates)
```
---
version: "2"
services:
  invoice-ninja:
    image: invoiceninja/invoiceninja:alpine-4
    container_name: invoice-ninja
    environment:
      - APP_URL=${URL}
      - APP_KEY=${APP_KEY}
      - MULTI_DB_ENABLED=false
      - DB_TYPE=mysql
      - DB_HOST1=ninja_db
      - DB_DATABASE=ninja_db
      - DB_USERNAME=invoice_ninja
      - DB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/Invoice-Ninja/public:/var/app/public
      - /portainer/Files/AppData/Config/Invoice-Ninja/storage:/var/app/storage
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on:
      - ninja_db
  ninja_db:
    image: linuxserver/mariadb
    container_name: ninja_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=ninja_db
      - MYSQL_USER=invoice_ninja
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/Invoice-Ninja/DB:/config
    restart: unless-stopped
```
Here are the logs:
```

Configuration cache cleared!


Configuration cached successfully!


[10-Jun-2020 16:49:30] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root


[10-Jun-2020 16:49:30] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root


[10-Jun-2020 16:49:30] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root


[10-Jun-2020 16:49:30] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root


[10-Jun-2020 16:49:30] NOTICE: fpm is running, pid 1


[10-Jun-2020 16:49:30] NOTICE: ready to handle connections
```

**Comment by codedge** [comment]
I cannot see any error there. You also mix env vars from IN 5, like `DB_HOST1`, with IN 4. This does not work. Do you want to use IN 4 or 5? - keep in mind, that IN 5 is in alpha state.

I'll add a separate docker-compose for IN or you can have a look about all correct [env variables here](https://github.com/invoiceninja/invoiceninja/blob/master/.env.example)

**Comment by SelfhostedPro** [comment]
I want to use IN 4 I guess I was a bit confused on the environment variables. Is that link all env variables for IN 4?

**Comment by codedge** [comment]
Yes, that link contains all possbile env variables that can be used for IN 4.

**Comment by codedge** [comment]
To get an idea how different the environment vars are, please see this page: https://github.com/invoiceninja/dockerfiles/wiki/differences-version-4-and-5. There are also [guides](https://github.com/invoiceninja/dockerfiles/wiki) how to set up IN 4 or 5.

**Comment by maxiride** [comment]
Having the same issue: "Connection reset by Peer". I've double-checked the env variables too, how did @SelfhostedPro solved the issue?

I've basically followed the IN 4 [guide](https://github.com/invoiceninja/dockerfiles/wiki/docker-compose-with-caddy#guide-for-invoice-ninja-4) and stripping out the Caddy service as I already have a webserver running.

docker-compose file:
```yml
version: '3.7'

services:
  app:
    image: invoiceninja/invoiceninja:alpine-4
    restart: always
    cap_add:
      - SYS_ADMIN
    ports:
      - 1546:9000
    environment:
      - APP_URL=redacted
      - APP_KEY=redacted
      - MULTI_DB_ENABLED=false
      - DB_HOST=db
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - DB_DATABASE=db-ninja-01
    volumes:
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      - mysql-data:/var/lib/mysql:rw
    networks:
      - invoiceninja

volumes:
  mysql-data:
  public:
  storage:

networks:
  invoiceninja:

````


Application log:
```
Configuration` cache cleared!,
Configuration cached successfully!,
[03-Dec-2020 15:20:34] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root,
[03-Dec-2020 15:20:34] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root,
[03-Dec-2020 15:20:34] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root,
[03-Dec-2020 15:20:34] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root,
[03-Dec-2020 15:20:34] NOTICE: fpm is running, pid 1,
[03-Dec-2020 15:20:34] NOTICE: ready to handle connections,
```
