### ISSUE TITLE
Re-deploy of container resets state even with volume persistence?

### ISSUE THREAD

**Issue by decentral1se** [invoiceninja/dockerfiles#167]
I am running the following invoiceninja docker swarm deployment from a  docker-compose.yml file listed below. Each time I run `docker stack deploy invoiceninja`, the app comes up fine and I need to go to `/setup` to fill in my details. Now, if I `docker stack rm invoiceninja` then the app goes down. The volumes are not destroyed. The application data should be persisted. Now, when I `stack deploy invoiceninja` once again, I am brought once more to `/setup` to re-fill in details. I am not sure if I have lost my data or if I have the wrong configuration. Any tips?

I am following the docs for https://github.com/invoiceninja/dockerfiles#create-folders-for-data-persistence.

Thanks :+1: 

```yaml
---
version: "3.8"

services:
  nginx:
    image: "nginx:stable"
    environment:
      - DOMAIN=foo.com
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    volumes:
      - "public:/var/www/app/public"
    networks:
      - proxy
      - internal
    depends_on:
      - invoiceninja
      - mariadb
    deploy:
      update_config:
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.invoiceninja.loadbalancer.server.port=80"
        - "traefik.http.routers.invoiceninja.rule=Host(`foo.com`)"
        - "traefik.http.routers.invoiceninja.entrypoints=web-secure"
        - "traefik.http.routers.invoiceninja.tls.certresolver=production"

  invoiceninja:
    image: "invoiceninja/invoiceninja:4.5.18"
    volumes:
      - "public:/var/www/app/public"
      - "storage:/var/www/app/storage"
    secrets:
      - api_secret
      - app_key
      - db_passwd
    environment:
      - APP_CIPHER=AES-256-CBC
      - APP_DEBUG=false
      - APP_ENV=production
      - APP_LOCALE=en
      - APP_URL=foo.com
      - DB_DATABASE=ninja
      - DB_HOST=mariadb
      - DB_STRICT=false
      - DB_TYPE=mysql
      - DB_USERNAME=ninja
      - LOG=single
      - REQUIRE_HTTPS=false
      - SESSION_ENCRYPT=true
      - SESSION_SECURE=true
      - TRUSTED_PROXIES="*"

      # Note(decentral1se): this isnt supported until the v5 tag stabilises so
      # when you end up on the initial /setup URL, you need to copy in the
      # password. Once v5 is out, this will be seemless
      - API_SECRET_FILE=/run/secrets/api_secret
      - APP_KEY_FILE=/run/secrets/app_key
      - DB_PASSWORD_FILE=/run/secrets/db_passwd

    depends_on:
      - mariadb
    networks:
      - internal

  mariadb:
    image: "mariadb:10.5"
    environment:
      - MYSQL_DATABASE=ninja
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD_FILE=/run/secrets/db_passwd
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_passwd
    secrets:
      - db_root_passwd
      - db_passwd
    volumes:
      - "mariadb:/var/lib/mariadb"
    networks:
      - internal

volumes:
  mariadb:
  public:
  storage:

networks:
  proxy:
    external: true
  internal:

secrets:
  db_root_passwd:
    name: invoiceninja_db_root_passwd_v1
    external: true
  db_passwd:
    name: invoiceninja_db_passwd_v1
    external: true
  app_key:
    name: invoiceninja_app_key_v1
    external: true
  api_secret:
    name: invoiceninja_api_secret_v1
    external: true

configs:
  nginx_conf:
    name: invoiceninja_nginx_conf_v1
    file: nginx.conf.tmpl
    template_driver: golang
```

May be related to https://github.com/invoiceninja/dockerfiles/issues/163 but I am not sure.
