### ISSUE TITLE
There appears to be a problem with your configuration, please check your .env file. If you've run 'php artisan config:cache' you will need to run 'php artisan config:clear'

### ISSUE THREAD

**Issue by karneaud** [invoiceninja/dockerfiles#172]
# Error 

> There appears to be a problem with your configuration, please check your .env file.
> If you've run 'php artisan config:cache' you will need to run 'php artisan config:clear'

# Setup information
Raspberry pi 3 B+
Docker version 19.03.7, build 7141c19
Docker Compose version 1.23.2, build 1110ad0
Invoice Ninja version: 4.5.18

Dockerfile
```
ARG PHP_VERSION=7.3

# Get Invoice Ninja
FROM arm32v7/alpine:latest as base

ARG INVOICENINJA_VERSION=4.5.18
ENV INVOICENINJA_VERSION ${INVOICENINJA_VERSION}

RUN set -eux; \
    apk add --no-cache \
    curl \
    libarchive-tools; \
    mkdir -p /var/www/app

RUN echo "Installing Invoice Ninja version $INVOICENINJA_VERSION"; \
	curl -o /tmp/ninja.tar.gz -LJ0 https://github.com/invoiceninja/invoiceninja/tarball/v$INVOICENINJA_VERSION \
    && bsdtar --strip-components=1 -C /var/www/app -xf /tmp/ninja.tar.gz \
    && rm /tmp/ninja.tar.gz \
    && cp -R /var/www/app/storage /var/www/app/docker-backup-storage  \
    && cp -R /var/www/app/public /var/www/app/docker-backup-public  \
    && mkdir -p /var/www/app/public/logo /var/www/app/storage \
    && cp /var/www/app/.env.example /var/www/app/.env \
#   && cp /var/www/app/.env.dusk.example /var/www/app/.env.dusk.local \
    && rm -rf /var/www/app/docs /var/www/app/tests

# Install nodejs packages
FROM arm32v7/node:12-alpine as frontend

COPY --from=base /var/www/app /var/www/app
WORKDIR /var/www/app/

RUN npm install --no-audit --production --nodev

# Prepare php image
FROM arm32v7/php:${PHP_VERSION}-fpm-alpine

ARG INVOICENINJA_VERSION=5.0.12-release
ARG INVOICENINJA_USER=invoiceninja
ARG INVOICENINJA_USERID=101

ENV INVOICENINJA_VERSION ${INVOICENINJA_VERSION}

LABEL maintainer="Samuel Laulhau <sam@lalop.co>, Holger Lösken <holger.loesken@codedge.de>"

WORKDIR /var/www/app

COPY --from=frontend /var/www/app /var/www/app

COPY entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

RUN echo "Using PHP version ${PHP_VERSION}"; \
	set -eux; \
    apk add --no-cache \
    freetype-dev \
    gmp-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev; \
    docker-php-ext-configure zip --with-libzip; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/; \
    docker-php-ext-install -j$(nproc) \
        bcmath \
        exif \
        gd \
        gmp \
        mbstring \
        mysqli \
        opcache \
        pdo \
        pdo_mysql \
        zip

ADD php.ini /usr/local/etc/php/php.ini
ADD php-cli.ini /usr/local/etc/php/php-cli.ini
COPY .env /var/www/app/.env
## USER

RUN echo "Adding user ${INVOICENINJA_USER} as ${INVOICENINJA_USERID} with $INVOICENINJA_VERSION"; \
	addgroup --g ${INVOICENINJA_USERID} ${INVOICENINJA_USER}
    
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "${INVOICENINJA_USER}" \ 
    --uid "${INVOICENINJA_USERID}" \
    --no-create-home \
    -D "${INVOICENINJA_USER}"; \
    chown -R "$INVOICENINJA_USER":"$INVOICENINJA_USER" /var/www/app

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; \
    composer global require hirak/prestissimo;

USER ${INVOICENINJA_USER}

RUN composer install --no-dev --no-suggest --no-progress --prefer-dist

ENTRYPOINT ["docker-entrypoint"]
CMD ["php-fpm"]
```

docker-compose.yml
```
version: "3.2"

services:
  php-fpm:
      image: arm32v7/invoiceninja:php7.3-fpm
      container_name: invoiceninja
      working_dir: /var/www/app
      environment:
        INVOICENINJA_VERSION: 4.5.18
        APP_ENV: local
        DB_PASSWORD: xxxxx
        MAIL_PASSWORD:xxxxxx
        PHANTOMJS_CLOUD_KEY:xxxxx
        GOOGLE_MAPS_API_KEY: xxx
      volumes:
        - invoiceninja:/var/www/app
      privileged: true
      ports:
        - 9000:9000
      hostname: php-fpm
      read_only: false
      entrypoint: ['docker-entrypoint']
      command: ['php-fpm']
  web:
    image: arm32v7/nginx:latest
    container_name: invoiceninja_nginx
    working_dir: /var/www/app
    privileged: true
    depends_on:
      - php-fpm
    volumes:
      - invoiceninja:/var/www/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    ports:
      - 8000:80
      - 4430:443
    command: [nginx-debug, '-g', 'daemon off;']
volumes:
    invoiceninja:
```

docker-entrypoint

```
#!/usr/bin/env sh
set -e

# logging functions
in_log() {
        local type="$1"; shift
        printf '%s [%s] [Entrypoint]: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$type" "$*"
}

in_error() {
        in_log ERROR "$@" >&2
        exit 1
}

# Indirect expansion (ie) is not supported in bourne shell. That's why we are using this "magic" here.
ie_gv() {
        eval "echo \$$1"
}

# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
        local var="$1"
        local fileVar="${var}_FILE"
        local def="${2:-}"

        if [ "$(ie_gv ${var})" != ""  ] && [ "$(ie_gv ${fileVar})" != "" ]; then
                in_error "Both $var and $fileVar are set (but are exclusive)"
        fi

        local val="$def"
        if [ "$(ie_gv ${var})" != "" ]; then
                val=$(ie_gv ${var})
        elif [ "$(ie_gv ${fileVar})" != "" ]; then
                val=`cat $(ie_gv ${fileVar})`
        fi

        export "$var"="$val"
        unset "$fileVar"
}

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

BAK_STORAGE_PATH=/var/www/app/docker-backup-storage/
BAK_LOGO_PATH=/var/www/app/docker-backup-public/logo/

if [ ! -d /var/www/app/storage ]; then
    cp -Rp $BAK_STORAGE_PATH /var/www/app/storage
else
    if [ -d $BAK_STORAGE_PATH ]; then
        IN_STORAGE_BACKUP="$(ls $BAK_STORAGE_PATH)"
        for path in $IN_STORAGE_BACKUP; do
            if [ ! -e "/var/www/app/storage/$path" ]; then
                cp -Rp "$BAK_STORAGE_PATH/$path" "/var/www/app/storage/"
            fi
        done
    fi
fi

if [ ! -d /var/www/app/public/logo ] && [ -d $BAK_LOGO_PATH ]; then
    cp -Rp $BAK_LOGO_PATH /var/www/app/public/logo
else
    if [ -d $BAK_LOGO_PATH ]; then
        IN_LOGO_BACKUP="$(ls $BAK_LOGO_PATH)"
        for path in $IN_LOGO_BACKUP; do
            if [ ! -e "/var/www/app/public/logo/$path" ]; then
                cp -Rp "$BAK_LOGO_PATH/$path" "/var/www/app/public/logo/"
            fi
        done
    fi
fi

# compare public volume version with image version
if [ ! -e /var/www/app/public/version ] || [ "$INVOICENINJA_VERSION" != "$(cat /var/www/app/public/version)" ]; then
    cp -au /var/www/app/docker-backup-public/* /var/www/app/public/
    echo $INVOICENINJA_VERSION > /var/www/app/public/version
fi

# Initialize values that might be stored in a file
file_env 'APP_KEY'
file_env 'API_SECRET'
file_env 'CLOUDFLARE_API_KEY'
file_env 'DB_USERNAME'
file_env 'DB_HOST'
file_env 'DB_DATABASE'
file_env 'MAIL_DRIVER'
file_env 'APP_CIPHER'
file_env 'REQUIRE_HTTPS'
file_env 'MAIL_HOST'
file_env 'MAIL_PORT'
file_env 'MAIL_USERNAME'
file_env 'MAILGUN_SECRET'
file_env 'S3_KEY'
file_env 'S3_SECRET'

# Run Laravel stuff
php artisan key:generate
php artisan config:cache
php artisan optimize

exec docker-php-entrypoint "$@"
```

If I `php artisan config:cache` and `php artisan config:clear` I get

> (1/1) RuntimeException No application encryption key has been specified at EncryptionServiceProvider-
> key(array('name' => 'Invoice Ninja', 'debug' => true, 'env' => 'local', 'url' => 'xxxx:8000', 'timezone' => 'UTC', 'locale' => 'en', 'fallback_locale' => 'en', 'key' => '', 'cipher' => '', 'log' => 'syslog', 'providers' => array('Illuminate\\Auth\\AuthServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider',

my .env

```
APP_KEY=base64:Wp2vjYLjaE9vzQsPbF8fmy1ebUZEENyIr9rVAV4mF+4 // default key
APP_LOG_LEVEL=error
APP_DEBUG=true
NINJA_VERSION_SUFFIX=''
LOG=syslog
DB_USERNAME=xxxxx
DB_HOST=xxxxx
DB_DATABASE=xxxxx
MAIL_HOST=xxxxx
MAIL_USERNAME='xxxx'
MAIL_DRIVER=smtp
MAIL_FROM_NAME=''
MAIL_FROM_ADDRESS="xxxxxxx"
MAIL_PORT=465
MAIL_ENCRYPTION=ssl
REQUIRE_HTTPS=false
TRUSTED_PROXIES='*'
SESSION_ENCRYPT=true
SESSION_SECURE=true
GOOGLE_MAPS_ENABLED=true
SESSION_DRIVER=file
CACHE_DRIVER=file
APP_CIPHER=AES-256-CBC
```

see https://stackoverflow.com/questions/62821760/laravel-env-problem-with-the-configuration for any other details
