### ISSUE TITLE
502 Error while using Nginx with Docker

### ISSUE THREAD

**Issue by orangethakkali** [invoiceninja/dockerfiles#177]
```
version: '3.7'

services:
  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    environment:
      - APP_URL=http://localhost
      - APP_KEY=base64:RxS03YnEQhrjadyi/QPJBon9MOR2DWAJ61IijOKa9F8=
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  /var/invoiceninja/public:/var/www/app/public:rw,delegated
      -  /var/invoiceninja/storage:/var/www/app/storage:rw,delegated
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
    ports:
      - "127.0.0.1:8046:9000"
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      #- mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - /var/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

networks:
  invoiceninja:

```
This is the docker-compose file I am using with Nginx reverse proxy. I get 502 error when I access https://domain.com. I have set 1001:101 to public and storage folder. On Nginx, I use `proxy_pass http://localhost:8046`.Anything I'm missing here.
