### ISSUE TITLE
invoiceninja + traefik = ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by w4tzmann** [invoiceninja/dockerfiles#180]
Hi,

is there someone who can help me running invoiceninja behind traefik?

Other apps (e .g. mailcow, grafana, portainer) are working fine. But when i try to open invoiceninja in the browser i only get "ERR_TOO_MANY_REDIRECTS"

Thats my docker-compose.yml:

```
version: '3.7'

services:
  server:
    image: caddy:alpine
    restart: always
    environment:
      - APP_URL=https://invoiceninja.tld
    volumes:
      # Vhost configuration
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      #-  public:/var/www/app/public
      #-  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./data/public:/var/www/app/public:rw,delegated
      - ./data/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    #ports:
     # - "80:80"
     # - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoiceninja.entrypoints=http"
      - "traefik.http.routers.invoiceninja.rule=Host(`invoiceninja.tld`)"  ## Hier eure Domain eingeben ##
      - "traefik.http.middlewares.invoiceninja-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.invoiceninja.middlewares=invoiceninja-https-redirect"
      - "traefik.http.routers.invoiceninja-secure.entrypoints=https"
      - "traefik.http.routers.invoiceninja-secure.rule=Host(`invoiceninja.tld`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.invoiceninja-secure.tls=true"
      - "traefik.http.routers.invoiceninja-secure.service=invoiceninja"
      - "traefik.http.services.invoiceninja.loadbalancer.server.port=80"
      - "traefik.http.routers.invoiceninja.middlewares=secHeaders@file"
      - "traefik.docker.network=proxy"
    networks:
      - invoiceninja
      - proxy

  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    environment:
      - APP_URL=https://invoiceninja.tld
      - APP_KEY=%key%
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      #-  public:/var/www/app/public
      #-  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./data/public:/var/www/app/public:rw,delegated
      - ./data/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      #- mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./data/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja


  # cron:
  #   image: invoiceninja/invoiceninja
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     bash -c 'bash -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

volumes:
  mysql-data:
  public:
  storage:

networks:
  invoiceninja:
  proxy:
   external: true
```

Thank you in advance!
