### ISSUE TITLE
Only see NGINX default page after docker-compose up

### ISSUE THREAD

**Issue by gururise** [invoiceninja/dockerfiles#186]
Following directions for alpine-4 and NGINX, after installation, I only see the default "WELCOME TO NGINX" screen.

I used the following docker-compose file and after docker-compose up I see the following error indicating the ninja4_cron container failed...

```
OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
```

docker-compose file:

```
version: '3.7'

services:
  server:
    image: nginx:alpine
    restart: always
    environment:
      - APP_URL=http://invoice.mydomain.com
    volumes:
      # Vhost configuration
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and los>
      #- ./docker/app/public:/var/www/app/public:rw,delegated
      #- ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    #ports: 
    #  - "8105:80"
    #  - "443:443"
    expose:
      - 80
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:alpine-4
    restart: always
    environment:
      - APP_URL=http://invoice.mydomain.com
      - APP_KEY=hmoDudEqHBxrOE/iKNC3ig3oT9mxJQS8Invmx4i7pdg=
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and los>
      #- ./docker/app/public:/var/www/app/public:rw,delegated
      #- ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and los>
      #- ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

  cron:
    image: invoiceninja/invoiceninja:alpine-4
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - invoiceninja
volumes:
  mysql-data:
  public:
  storage:
  logo:

networks:
  invoiceninja:
```
