### ISSUE TITLE
Older install of IN4 via Docker Compose is stuck on 4.5.18 and can't be upgraded to 4.5.19

### ISSUE THREAD

**Issue by andrewhaji** [invoiceninja/dockerfiles#194]
Hi all,

I've been running IN4, self-hosted, via Docker, for months now. Works great. I followed the (older) install instructions from this wiki precisely. Had a bit of trouble when the invoiceninja:latest branch jumped up to 5.0, but I managed to get back to 4.x by updating the docker-compose file to show invoiceninja:4.5.18.

Now, I see 4.5.19 is available, but only in an alpine variety. I tried updating my docker-compose file to refer to invoiceninja:alpine-4 instead of invoiceninja:4.5.18, but when I try to bring it up the cron container crashes instantly and the app container restarts continuously.

I've noticed that the dockerfiles and sample docker-compose files on this repository have been completely rewritten in the last few months. Is there any way to transition my older docker-compose install to the current one, allowing me to move up to 4.5.19 (and eventually migrate to 5.0)?

Many thanks for the help.

**Comment by codedge** [comment]
To help you I need the errors you face. How to get the errors you can see on the [**Debuggung and FAQ**](https://github.com/invoiceninja/dockerfiles/wiki/Debugging-&-FAQ) in the wiki.

Can you also paste your full docker-compose.yml please

I am pretty sure we get you to the latest 4.x version - after that, we can discuss about moving to 5.

**Comment by andrewhaji** [comment]
Here is my current docker-compose, before I've made any changes to it:

```
version: '3.6'

volumes:
  db:
  storage:
  logo:
  public:

# uncomment if you want to use external network (example network: "web")
#networks:
#  web:
#    external: true

services:
  db:
    image: mysql:5
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  app:
    image: invoiceninja/invoiceninja:4.5.18
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    networks: 
      - default  

  web:
    image: nginx:1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    expose: # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
      - "80"
    depends_on:
      - app
    ports: # Delete if you want to use reverse proxy
      - 8000:80
    networks:
#      - web        # uncomment if you want to use  external network (reverse proxy for example)
      - default

  cron:
    image: invoiceninja/invoiceninja:4.5.18
    env_file: .env
    restart: always
    depends_on:
      - web
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - default
```

I changed both references to `invoiceninja/invoiceninja:4.5.18` to `invoiceninja/invoiceninja:alpine-4` and ran `docker-compose up -d` again. Immediately I get the following error regarding the "cron" container:

```
Creating invoiceninja_cron_1 ... error

ERROR: for invoiceninja_cron_1  Cannot start service cron: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

ERROR: for cron  Cannot start service cron: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
```

When I look at the current (updated) docker-compose file from this wiki, it shows the "cron" container uses /bin/sh as an entrypoint instead of bash - maybe I just need to change that in my docker-compose file?

Running `docker ps` the invoiceninja_app_1 container shows `Restarting (1) 14 seconds ago`

When I run `docker-compose logs -f` I get a ton of errors similar to this:

```
app_1   | cp: can't preserve times of '/var/www/app/public/images/credit_cards': Operation not permitted
app_1   | cp: can't preserve ownership of '/var/www/app/public/images/credit_cards': Operation not permitted
app_1   | cp: can't preserve permissions of '/var/www/app/public/images/credit_cards': Operation not permitted
app_1   | cp: can't create '/var/www/app/public/images/about2@2x.jpg': File exists
app_1   | cp: can't create '/var/www/app/public/images/PersonalizeInvoiceColor.png': File exists
app_1   | cp: can't create '/var/www/app/public/images/AlertsWhenInvoicesViewed.png': File exists
app_1   | cp: can't create '/var/www/app/public/images/shalomstark.jpg': File exists
app_1   | cp: can't create '/var/www/app/public/images/report_logo3.jpg': File exists
app_1   | cp: can't create '/var/www/app/public/images/icon-secure-pay.png': File exists
app_1   | cp: can't create '/var/www/app/public/images/social.jpg': File exists
app_1   | cp: can't create '/var/www/app/public/images/hero-bg-plans.jpg': File exists
```

Perhaps an issue with file permissions? The volumes are docker named volumes so I don't manage the permissions myself.

Thank you so much for the help.
