### ISSUE TITLE
v5 not starting in docker on a Synology NAS with external MariaDB.

### ISSUE THREAD

**Issue by justsomebody42** [invoiceninja/dockerfiles#195]
I'm trying to get v5 running in docker on a Synology NAS with external MariaDB.

I'v compiled the below docker-compose.yml as I don't want to use an additional web server.

My understanding is that I could use the server running on port 9000.I found different paths for the volumes and am confused :slightly_smiling_face:
The docu here https://github.com/invoiceninja/dockerfiles/wiki/docker-only-setup states that /var/app/public (and storage) should be used, while the docker-compose here (https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose.yml) contains /var/www/app/public (and storage...)
The former seems to be for v4, but https://github.com/invoiceninja/dockerfiles/wiki/differences-version-4-and-5 only states the DB env values to be different.

When I use **/var/app/storage** in my compose file, the server seems to start, but does not respond the requests from the browser.
Logs:
```
Configuration cache cleared!
Configuration cached successfully!
Configuration cache cleared!
[26-Aug-2020 08:15:38] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[26-Aug-2020 08:15:38] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[26-Aug-2020 08:15:38] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[26-Aug-2020 08:15:38] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[26-Aug-2020 08:15:38] NOTICE: fpm is running, pid 1
[26-Aug-2020 08:15:38] NOTICE: ready to handle connections
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
les cached successfully!
```

When I use **/var/www/app/storage** the container does not start at all.
Logs:

```
chown: /var/www/app/storage: Operation not permitted
chown: /var/www/app/storage: Operation not permitted
chown: /var/www/app/public: Operation not permitted
chown: /var/www/app/public: Operation not permitted
```

Docker-compose:
```
version: "2.0"
services:
  invoiceninja5:
    image: invoiceninja/invoiceninja:5
    ports:
      - "3857:9000"
    volumes:
      - /volume1/docker/invoiceninja/public:/var/app/public:rw,delegated
      - /volume1/docker/invoiceninja/storage:/var/app/storage:rw,delegated
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL='http://192.168.1.110:3857'
      - APP_KEY='base64:...'
      - APP_CIPHER='AES-256-CBC'
      - MULTI_DB_ENABLED=false
      - DB_TYPE='mysql'
      - DB_STRICT='false'
      - DB_HOST1='192.168.1.110:3307'
      - DB_DATABASE1='invoiceninja5'
      - DB_USERNAME1='invoiceninja5'
      - DB_PASSWORD1='...'
```
