### ISSUE TITLE
Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied "

### ISSUE THREAD

**Issue by alexdmejias** [invoiceninja/dockerfiles#197]
I get the following error when I try to configure the email settings in the System Settings page. I'm using a office 365 email address but I have also tried with a different email provider entirely

# Logs

Did you check the logs ?
If any Error is present there please copy/paste it below 
![image](https://user-images.githubusercontent.com/1284283/91875231-3a1d7c00-ec49-11ea-8e1f-047fa1b9ad93.png)
![image](https://user-images.githubusercontent.com/1284283/91878293-12c8ae00-ec4d-11ea-9a72-a28f349ca184.png)

```
550 5.7.1 Relaying denied 
```

# Setup information

What version do you run?
v4.x.x
Do you run docker-compose or a single Dockerfile ?
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    environment: 
      - APP_URL=http://ninja.local
    volumes:
      # Vhost configuration
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/default.conf:ro

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      # -  public:/var/www/app/public
      # -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./volumes/public:/var/www/app/public:rw,delegated
      - ./volumes/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports: 
      - "80:80"
      # - "443:443"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:alpine-4
    restart: always
    environment: 
      - APP_URL=http://ninja.local
      - APP_KEY=base64:OA3IYUu4lPrBheDJZ8/HLR8U3UFvEJrPWbolk1VEKi0=
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_HOST=db
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - DB_DATABASE=ninja
      - APP_DEBUG=true
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      # -  public:/var/www/app/public
      # -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./volumes/public:/var/www/app/public:rw,delegated
      - ./volumes/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks: 
      - invoiceninja  

  db:
    image: mysql:5
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
  # cron:
  #   image: invoiceninja/invoiceninja:alpine-4
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     /bin/sh -c 'sh -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

volumes:
  mysql-data:
  public:
  storage:
  # This is needed for letting th cron run correctly
  # logo:

networks:
  invoiceninja:
```
