### ISSUE TITLE
Provide a docker-compose reference configuration for Traefik 2

### ISSUE THREAD

**Issue by PhilippMolitor** [invoiceninja/dockerfiles#199]
As I do not want to dedicate a whole server only to InvoiceNinja, I am running that server with Traefik as a reverse proxy.
I tried both Caddy and NGINX as http-only web servers which i connected to Traefik, but nothing seems to work properly. The furthest i got was to the setup page, but due to some protocol errors the setup.js file does not load and the setup is only spitting out 50X errors.

Could you provide a reference configuration when running behind Traefik 2?

**Comment by hillelcoren** [comment]
Maybe this will help:

https://blog.ktz.me/how-to-setup-invoiceninja-v4-with-traefik-v2-nginx-with-tls/

**Comment by PhilippMolitor** [comment]
That seemed to help, although the PDF renderer seems to be unavailable (passing internal server errors).

**Comment by Janl1** [comment]
PDF rendering issue is #196

**Comment by fenpaws** [comment]
@PhilippMolitor if you have your Traefik2 already set up then all you need is to put this under the Nginx service in the docker-compose file. 

This handles HTTP and HTTPS requests, HTTP will automatically be redirected to HTTPS.

```yaml
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.kazucreations_invoice5_ssl.rule=Host(`DOMAN.COM`)
      - traefik.http.routers.kazucreations_invoice5_ssl.entrypoints=websecure
      - traefik.http.routers.kazucreations_invoice5_ssl.tls.certresolver=letsencrypt
      - traefik.http.services.kazucreations_invoice5.loadbalancer.server.port=80
      # HTTP
      - traefik.http.routers.kazucreations_invoice5.rule=Host(`DOMAN.COM`)
      - traefik.http.routers.kazucreations_invoice5.entrypoints=web
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.kazucreations_invoice5.middlewares=redirect-to-https
```

**Comment by fenpaws** [comment]
Also, here is a Traefik 2 compose file that works, it's based on my private one. 

I mont the `acme.json` locally since I don't want to use volumes for that. So you need to create an `acme.json` file and give it `600` pfemissions.

```yml
version: "3"
services:
  app:
    image: traefik:2.4
    command:
      # defines all entryPoints
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"  

      # SSL
      - "--log.level=INFO"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=EMAIL@EMAIL.COM"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      # TESTING ONLY: LetsEncryp staging certs without rate limit 
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

      # enabled docker provide
      - "--providers.docker"

      # api on http
      - "--api.insecure=true"

      # disable https cert checks for local/lan servers
      - "--serversTransport.insecureSkipVerify=true"

      - "--providers.docker.exposedByDefault=false"

    environment:
      - TZ=Europe/Berlin
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./acme.json:/letsencrypt/acme.json
    #  - ./config/:/etc/traefik/config

      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: host
```
