### ISSUE TITLE
Debugging (web UI bar) is turned on by default, impossible to turn off

### ISSUE THREAD

**Issue by maxguru** [invoiceninja/dockerfiles#20]
It seems that no matter what, debugging is turned on and impossible to turn off through the check box in web UI.

**Comment by hillelcoren** [comment]
I'm not sure, I'm not able to replicate this.

Have you tried manually editing the .env file.

**Comment by maxguru** [comment]
I will try to do it, but the feature is definitely broken with deployed with docker-compose.

**Comment by maxguru** [comment]
I checked and it looks like `APP_DEBUG=false` in `.env` file, but it still shows the PHP debug bar at the bottom of the browser window.

**Comment by lalop** [comment]
@maxguru can you share your `docker-compose.yml` file please ?

**Comment by maxguru** [comment]
```
version: "2"

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ninja
      MYSQL_ROOT_PASSWORD: somethingsomething

  app:
    image: invoiceninja/invoiceninja
    links:
      - db:mysql
    environment:
      APP_DEBUG: 1
      DB_USERNAME: root
      DB_PASSWORD: somethingsomething
    volumes:
      - ./data/storage:/var/www/app/storage
      - ./data/logo:/var/www/app/public/logo

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    ports:
      - "80:80"

  cron:
    image: invoiceninja/invoiceninja
    links:
      - db:mysql
    user: www-data
    environment:
      APP_DEBUG: 1
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        DB_USERNAME=root DB_PASSWORD=somethingsomething /usr/local/bin/php /var/www/app/artisan ninja:send-invoices
        DB_USERNAME=root DB_PASSWORD=somethingsomething /usr/local/bin/php /var/www/app/artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    volumes_from:
      - app
```

I have customized nginx.conf to make things work right with a reverse proxy.

By the way, I had to `chmod a+rwx data/*` to make it work.  Also, see issue #18.
