### ISSUE TITLE
The Crons need to be enabled

### ISSUE THREAD

**Issue by Rustymage** [invoiceninja/dockerfiles#200]
# Issue

Logged into website, setup and onto the main page. I am getting this warning triangle:

<img width="400" alt="Screenshot 2020-10-14 at 12 13 50" src="https://user-images.githubusercontent.com/19926955/95981588-c8734900-0e16-11eb-8ef0-7f0e66c8c861.png">

# Logs

Please tell me which logs are best?

```
N/A
```

# Setup information

Ubuntu Server 20.04

docker-compose.yml
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    environment:
      - APP_URL=https://URL.co.uk
    volumes:
      # Vhost configuration
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
#      -  public:/var/www/app/public
#      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./public:/var/www/app/public:rw,delegated
      - ./storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "8000:80"
#     - "443:443"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    environment:
      - APP_URL=https://URL.co.uk
      - APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXX
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
#      -  public:/var/www/app/public
#      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./public:/var/www/app/public:rw,delegated
      - ./storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
#      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to acc>
      - ./mysql:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
#  cron:
#     image: invoiceninja/invoiceninja:alpine-4
#     volumes:
#      -  storage:/var/www/app/storage
#      -  logo:/var/www/app/public/logo
#      -  public:/var/www/app/public
#     entrypoint: |
#       /bin/sh -c 'sh -s <<EOF
#       trap "break;exit" SIGHUP SIGINT SIGTERM
#       sleep 300s
#       while /bin/true; do
#         ./artisan ninja:send-invoices
#         ./artisan ninja:send-reminders
#         sleep 1d
#       done
#       EOF'
#     networks:
#       - invoiceninja

#volumes:
#  mysql-data:
#  public:
#  storage:
  # This is needed for letting th cron run correctly
#  logo:

networks:
  invoiceninja:
```
