### ISSUE TITLE
DB credentials not being applied to db container

### ISSUE THREAD

**Issue by arcreigh** [invoiceninja/dockerfiles#202]
# Error log from db_1
```
db_1      | 2020-10-16T14:45:55.813689Z 2 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T14:45:55.892297Z 3 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T14:45:57.420861Z 4 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T14:45:57.421919Z 5 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T14:47:17.480945Z 6 [Note] Access denied for user 'root'@'localhost' (using password: NO)
db_1      | 2020-10-16T14:47:42.683459Z 7 [Note] Access denied for user 'ninja'@'localhost' (using password: NO)
db_1      | 2020-10-16T14:47:49.687977Z 8 [Note] Access denied for user 'ninja'@'localhost' (using password: YES)
db_1      | 2020-10-16T14:51:02.686555Z 9 [Note] Access denied for user 'root'@'localhost' (using password: NO)
db_1      | 2020-10-16T14:51:11.295856Z 10 [Note] Access denied for user 'root'@'localhost' (using password: YES)
db_1      | 2020-10-16T15:05:25.522614Z 11 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T15:05:25.524638Z 12 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T15:05:25.876386Z 13 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T15:05:25.877540Z 14 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T15:06:28.467799Z 15 [Note] Access denied for user 'ninja'@'172.24.0.4' (using password: YES)
db_1      | 2020-10-16T16:06:40.035489Z 16 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)
db_1      | 2020-10-16T16:06:40.036427Z 17 [Note] Access denied for user ''@'172.24.0.4' (using password: NO)

```

# Environment information

invoiceninja version 5
host OS ubuntu 18.04 LTS
the host OS is a VM running in vSphere w/ 4gigs of ram 50 gigs of storage and 2vCPU's
Running docker-compose version 1.27.4, build 40524192
Running Docker version 19.03.6, build 369ce74a3c

# docker-compose.yml
I left mostly defaults as I wanted to test out the image before going production. 
The hostname is only resolvable internal to my network. 
```
version: '3.7'

services:
  server:
    image: caddy:alpine
    restart: always
    environment:
      - APP_URL=http://ninja.arc.net
    volumes:
      # Vhost configuration
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "80:80"
      - "443:443"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    cap_add:
      - SYS_ADMIN
    environment:
      - APP_URL=http://ninja.arc.net
      - APP_KEY=base64:REDACTED_APP_KEY
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
  # cron:
  #   image: invoiceninja/invoiceninja:alpine-4
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     /bin/sh -c 'sh -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

volumes:
  mysql-data:
  public:
  storage:
  # This is needed for letting th cron run correctly
  # logo:

networks:
  invoiceninja:
```
# Additional questions.

- How would one go about building this image through portainer?
Currently I am following the wiki instructions to get the web UI running. 
- If I change the public / storage locations and give it the correct permissions of 1000:www-data
1000 being the default user created on installation
The UI breaks entirely as the javascript returns 500 errors when trying to load them. Additionally going to /var/invoiceninja/public or /storage (on the host OS not within the container) reveals that no data is saved there.
I am fairly new to Docker so I am not sure if I am missing something vital here in order for a container to access host level directories. Any input here would be much appreciated.
