### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ninjasifr.accounts' doesn't exist (SQL: select * from `accounts` limit 1)

### ISSUE THREAD

**Issue by Aerya** [invoiceninja/dockerfiles#210]
Hi,

Followed all the guides and https://github.com/invoiceninja/dockerfiles/wiki/prerequisites.

Here's my docker-compose
```
version: '3'

services:
  server:
    image: nginx
    restart: always
    container_name : invoiceninja5nginx
    environment: 
      - APP_URL=https://ivn.xx.fr
    volumes:
      # Vhost configuration
      - /home/xx/docker/si/invoiceninja5/invoiceninja5/config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - /home/xx/docker/si/invoiceninja5/public:/var/www/app/public
      - /home/xx/docker/si/invoiceninja5/storage:/var/www/app/storage
    depends_on:
      - app
    ports: 
      - "8963:80"
      - "8964:443"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:latest
    restart: always
    container_name : invoiceninja5
    cap_add:
      - SYS_ADMIN
    environment: 
      - APP_URL=https://ivn.xx.fr
      - APP_DEBUG=true
      - APP_KEY=base64:xx=
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_USERNAME1=xx
      - DB_PASSWORD1=xx
      - DB_DATABASE1=xx
    volumes:
      - /home/xx/docker/si/invoiceninja5/public:/var/www/app/public
      - /home/xx/docker/si/invoiceninja5/storage:/var/www/app/storage
    depends_on:
      - db
    networks: 
      - invoiceninja
    labels:
      - com.centurylinklabs.watchtower.enable=true

  db:
    image: mysql:5
    restart: always
    container_name : invoiceninja5db
    environment: 
      - MYSQL_ROOT_PASSWORD=xx
      - MYSQL_USER=xx
      - MYSQL_PASSWORD=xx
      - MYSQL_DATABASE=xx
    volumes:
      - /home/xx/docker/si/invoiceninja5/mysql-data:/var/lib/mysql:rw
    networks:
      - invoiceninja
    labels:
      - com.centurylinklabs.watchtower.enable=true


networks:
  invoiceninja:
```
