### ISSUE TITLE
CRON Container in v5 EXIT CODE: 127

### ISSUE THREAD

**Issue by Condolas** [invoiceninja/dockerfiles#252]
The cron container exits with error code 127. Running docker-compose on v5.0.43-p1 dockerfiles. 

Please see the logs below:

```
Configuration cache cleared!,
Configuration cached successfully!,
Configuration cache cleared!,
Configuration cached successfully!,
Route cache cleared!,
Routes cached successfully!,
les cached successfully!,
/usr/local/bin/docker-php-entrypoint: exec: line 9: cron.sh: not found,
```

**Comment by turbo124** [comment]
hi @Condolas this was a regression, if you pull the new image this issue is resolved.

also in your docker-compose, you'll need to add this line in to mount the cron.sh file
```
  cron:
    image: invoiceninja/invoiceninja:5
    env_file: env
    volumes:
      - ./config/cron.sh:/usr/local/bin/cron.sh
```
