### ISSUE TITLE
SQLSTATE[23000] on InvoiceNinja4

### ISSUE THREAD

**Issue by IrealiTY** [invoiceninja/dockerfiles#266]
After learning how to connect to a different MySQL server that is "not part" of the stack I managed to finally connect to it (I was being dumped and used the wrong container name). I managed to get IN4 running with the following error:

# Logs

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ninja`.`gateways`, CONSTRAINT `gateways_payment_library_id_foreign` FOREIGN KEY (`payment_library_id`) REFERENCES `payment_libraries` (`id`) ON DELETE CASCADE) (SQL: insert into `gateways` (`name`, `provider`, `sort_order`, `updated_at`, `created_at`) values (Authorize.Net AIM, AuthorizeNet_AIM, 5, 2021-01-24 17:23:19, 2021-01-24 17:23:19))
```

I can access /setup URL hoping it was simply not populating the MySQL database but nope, sadly same error.
But, the databases seem populated normally.
![image](https://user-images.githubusercontent.com/1223686/105638472-b15ae300-5e6a-11eb-86c6-7a00950a6962.png)
![image](https://user-images.githubusercontent.com/1223686/105638484-bfa8ff00-5e6a-11eb-9199-a1500b5dc809.png)

(I created the databases myself as, my understanding was that the docker-compose was doing that, and since I removed that section I had to do it myself)

# Setup information
- Synology with Docker
- Database in a separate docker container 
- Adjusted docker-compose.yml
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    ports: 
      - "804:80"
      #- "443:443"
    networks:
      - mynet

  app:
    image: invoiceninja/invoiceninja:alpine-4
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    networks:
      - mynet

  cron:
    image: invoiceninja/invoiceninja:alpine-4
    volumes:
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./docker/app/public/logo:/var/www/app/public/logo:rw,delegated
    entrypoint: |
      /bin/sh -c 'sh -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - mynet

networks:
  mynet:
    name: mynet
```

ENV File
```
APP_URL=http:/192.168.1.67:804/
APP_KEY=base64:mykeyhere_is_actually_different
APP_DEBUG=true
MULTI_DB_ENABLED=false
DB_HOST1=mariadb_mariadb_1
DB_USERNAME1=ninja
DB_PASSWORD1=ninja
DB_DATABASE1=ninja

#this is a system variable please do not remove
IS_DOCKER=true

#V4 env vars
DB_STRICT=false
DB_HOST=mariadb_mariadb_1
DB_DATABASE=ninja
DB_USERNAME=ninja
DB_PASSWORD=ninja
APP_CIPHER=AES-256-CBC
```
