### ISSUE TITLE
mysql: not found 

### ISSUE THREAD

**Issue by electronick86** [invoiceninja/dockerfiles#267]
Hello,

I try to test invoiceninja based on the docker-compose file with just minor changes for the first test.

I have the following error once the `docker-compose up -d` is executed 

```
app_1     | Configuration cache cleared!
app_1     | Configuration cached successfully!
app_1     | Configuration cache cleared!
app_1     | Configuration cached successfully!
app_1     | Route cache cleared!
app_1     | Routes cached successfully!
app_1     | Files cached successfully!
app_1     | Migration table created successfully.
app_1     | Loading stored database schema: /var/www/app/database/schema/db-ninja-01-schema.dump
app_1     | 
app_1     | In Process.php line 257:
app_1     |                                                                                
app_1     |   The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_L  
app_1     |   OAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}  
app_1     |   " --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.  
app_1     |                                                                                
app_1     |   Exit Code: 127(Command not found)                                            
app_1     |                                                                                
app_1     |   Working directory: /var/www/app                                              
app_1     |                                                                                
app_1     |   Output:                                                                      
app_1     |   ================                                                             
app_1     |                                                                                
app_1     |                                                                                
app_1     |   Error Output:                                                                
app_1     |   ================                                                             
app_1     |   sh: mysql: not found                                                         
app_1     |                                                                                
app_1     | 
```

I don't understand how could I solve that. Any idea? Thanks!!!

```
#:/etc/docker/docker-compose-files/ivs.XXX.dev$ cat docker-compose.yml 
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    networks:
      - invoiceninja
      - traefik-web
    labels:
      - "traefik.frontend.rule=Host:ivs.XXX.dev"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik-web" 
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks: 
      - invoiceninja  
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  db:
    image: mysql:5
    ports:
      - "3304:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 5. DO NOT USE FOR IN 4.
  cron:
    image: invoiceninja/invoiceninja:5
    env_file: env
    volumes:
      - ./config/cron.sh:/usr/local/bin/cron.sh
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    command:
      - cron.sh
    depends_on:
      - app
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip


networks:
  invoiceninja:
  traefik-web:
    external: true
```

```
#:/etc/docker/docker-compose-files/ivs.XXX.dev$ cat env
APP_URL=http://ivs.XXX.dev/
APP_KEY=base64:vBaXvBNxxxxxxxxxxxxxxxfzpt58FXI5UJFbBMDu0qek=
APP_DEBUG=true
MULTI_DB_ENABLED=false
DB_HOST1=db
DB_USERNAME1=ninja
DB_PASSWORD1=ninja
DB_DATABASE1=ninja

#this is a system variable please do not remove
IS_DOCKER=true


TRUSTED_PROXIES='10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
```
