### ISSUE TITLE
failed to start in docker swarm mode with mariadb cluster proxy maxscale

### ISSUE THREAD

**Issue by GurjinderSingh** [invoiceninja/dockerfiles#313]
**Setup information**

```
version: '3.3'
services:
  invoiceninja:
    image: invoiceninja/invoiceninja
    extra_hosts:
     - invoice.*******.***:1.2.3.4
    environment:
      APP_DEBUG: 'true'
      APP_KEY: base64:Slr5+3K4pSDwvjlsIkqTyAe4sxsHrwB7ArOxkitZ7Pc=
      APP_URL: https://invoice.******.***/
      DB_DATABASE1: ninja
      DB_HOST1: maxscale
      DB_PASSWORD1: rootpassword
      DB_TYPE: MariaDB
      DB_PORT1: '3306'
      DB_USERNAME1: root
      MULTI_DB_ENABLED: 'false'
      IS_DOCKER: 'true'
      PHANTOMJS_PDF_GENERATION: 'false'
    volumes:
     - /gfdisk/gv1/invoiceninja/public:/var/www/app/public
     - /gfdisk/gv1/invoiceninja/storage:/var/www/app/storage
     - /gfdisk/gv1/invoiceninja/hosts:/etc/hosts
    networks:
     - caddy_caddy
     - mydbnet
    deploy:
      labels:
        caddy: invoice.*****.***
        caddy.1_root: '* /var/www/app/public'
        caddy.2_php_fastcgi: '{{upstreams 9000}}'
        caddy.3_encode: zstd gzip
        caddy.3_file_server: browse
      placement:
        constraints:
         - node.hostname == swarm-01
networks:
  caddy_caddy:
    external: true
  mydbnet:
    external: true

```

**Describe the bug - some points**
crashing 
using root db password to test. 
extra_hosts: using sub domain and ip of vps swarm-01 and have placement constraint to deploy only on that host.

**To reproduce**
1. docker system prune -a   << clean start
2. docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show  << output attached 
3. database user create with phpmyadmin < query attached
4. checking directory permission storage and public
5. docker stack deploy --compose-file docker-compose.yml invoiceninja
6. attached directory list of public and storage.

**step 2 output**
```
docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show


Unable to find image 'invoiceninja/invoiceninja:latest' locally
latest: Pulling from invoiceninja/invoiceninja
9aae54b2144e: Pull complete 
0552190813ec: Pull complete 
d6abf49ad7ff: Pull complete 
4a7b791901cf: Pull complete 
1a292e934b24: Pull complete 
b6e111bad055: Pull complete 
8507471fd42c: Pull complete 
f07e8b1ba7d9: Pull complete 
f0fa6f4125ae: Pull complete 
f3804fc82c59: Pull complete 
ad236fbb9c9c: Pull complete 
816159a7324d: Pull complete 
e36925e7372a: Pull complete 
1b6f2607247a: Pull complete 
93c2014f143d: Pull complete 
a3221a999caf: Pull complete 
496b15e1741f: Pull complete 
551250237094: Pull complete 
Digest: sha256:41b9222c5fc5bb0092c291d5dcfba56c082c05d421e434741a87ae90fd251ad4
Status: Downloaded newer image for invoiceninja/invoiceninja:latest
base64:Slr5+3K4pSDwvjlsIkqTyAe4sxsHrwB7ArOxkitZ7Pc=
```

**step 3 output**
```
CREATE USER 'ninja'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT USAGE ON *.* TO 'ninja'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `ninja`;GRANT ALL PRIVILEGES ON `ninja`.* TO 'ninja'@'%';GRANT ALL PRIVILEGES ON `ninja\_%`.* TO 'ninja'@'%'; 
```

**step 4 output**
```
drwxr-xr-x  2 1500 1500 4096 Mar 30 16:16 public
drwxrwxrwx  2 1500 1500 4096 Mar 30 16:17 storage
```

**step 5**

**Screenshots/logs**

```
jxy34  Initialising Laravel...
jxy34  Configuration cache cleared!
jxy34  Configuration cached successfully!
jxy34  Configuration cache cleared!
jxy34  Configuration cached successfully!
jxy34  Route cache cleared!
jxy34  Routes cached successfully!
jxy34  Files cached successfully!
jxy34  Migration table created successfully.
jxy34  Loading stored database schema: /var/www/app/database/schema/db-ninja-01-schema.dump
jxy34  Loaded stored database schema. (3,290.78ms)
jxy34  Migrating: 2020_10_22_204900_company_table_fields
jxy34  Migrated:  2020_10_22_204900_company_table_fields (66.28ms)
jxy34  Migrating: 2020_10_27_021751_tasks_invoice_documents
jxy34  Migrated:  2020_10_27_021751_tasks_invoice_documents (233.40ms)
jxy34  Migrating: 2020_10_28_224711_status_sort_order
jxy34  Migrated:  2020_10_28_224711_status_sort_order (90.19ms)
jxy34  Migrating: 2020_10_28_225022_assigned_user_tasks_table
jxy34  Migrated:  2020_10_28_225022_assigned_user_tasks_table (50.73ms)
jxy34  Migrating: 2020_10_29_001541_vendors_phone_column
jxy34  Migrated:  2020_10_29_001541_vendors_phone_column (94.11ms)
jxy34  Migrating: 2020_10_29_093836_change_start_time_column_type
jxy34  Migrated:  2020_10_29_093836_change_start_time_column_type (94.57ms)
jxy34  Migrating: 2020_10_29_204434_tasks_table_project_nullable
jxy34  Migrated:  2020_10_29_204434_tasks_table_project_nullable (167.82ms)
jxy34  Migrating: 2020_10_29_210402_change_default_show_tasks_table
jxy34  Migrated:  2020_10_29_210402_change_default_show_tasks_table (63.13ms)
jxy34  Migrating: 2020_10_30_084139_change_expense_currency_id_column
jxy34  Migrated:  2020_11_03_200345_company_gateway_fields_refactor (196.95ms)
jxy34  Migrating: 2020_11_08_212050_custom_fields_for_payments_table
jxy34  Migrated:  2020_11_08_212050_custom_fields_for_payments_table (43.51ms)
jxy34  Migrating: 2020_11_12_104413_company_gateway_rename_column
jxy34  Migrated:  2020_11_12_104413_company_gateway_rename_column (49.82ms)
jxy34  Migrating: 2020_11_15_203755_soft_delete_paymentables
jxy34  Migrated:  2020_11_15_203755_soft_delete_paymentables (47.35ms)
jxy34  Migrating: 2020_12_14_114722_task_fields
jxy34  Migrated:  2020_12_14_114722_task_fields (72.79ms)
jxy34  Migrating: 2020_12_17_104033_add_enable_product_discount_field_to_companies_table
jxy34  Migrated:  2020_12_17_104033_add_enable_product_discount_field_to_companies_table (47.95ms)
jxy34  Migrating: 2020_12_20_005609_change_products_table_cost_resolution
jxy34  Migrated:  2020_12_20_005609_change_products_table_cost_resolution (130.33ms)
jxy34  Migrating: 2020_12_23_220648_remove_null_values_in_countries_table
jxy34  Migrated:  2020_12_23_220648_remove_null_values_in_countries_table (16.63ms)
jxy34  Migrating: 2021_01_03_215053_update_canadian_dollar_symbol
jxy34  Migrated:  2021_01_03_215053_update_canadian_dollar_symbol (487.31ms)
jxy34  Migrating: 2021_01_05_013203_improve_decimal_resolution
jxy34  
jxy34  In Connection.php line 678:
jxy34  
jxy34    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
jxy34    ue for 'adjustment' (SQL: ALTER TABLE company_ledgers CHANGE adjustment adj
jxy34    ustment NUMERIC(20, 6) DEFAULT 'NULL', CHANGE balance balance NUMERIC(20, 6
jxy34    ) DEFAULT 'NULL')
jxy34  
jxy34  
jxy34  In Exception.php line 18:
jxy34  
jxy34    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
jxy34    ue for 'adjustment'
jxy34  
jxy34  
jxy34  In PDOStatement.php line 115:
jxy34  
jxy34    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
jxy34    ue for 'adjustment'
jxy34  
jxy34  
6wkzu  Initialising Laravel...
6wkzu  Configuration cache cleared!
6wkzu  Configuration cached successfully!
6wkzu  Configuration cache cleared!
6wkzu  Configuration cached successfully!
6wkzu  Route cache cleared!
6wkzu  Routes cached successfully!
6wkzu  Files cached successfully!
6wkzu  Migrating: 2021_01_05_013203_improve_decimal_resolution
6wkzu  
6wkzu  In Connection.php line 678:
6wkzu  
6wkzu    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
6wkzu    ue for 'adjustment' (SQL: ALTER TABLE company_ledgers CHANGE adjustment adj
6wkzu    ustment NUMERIC(20, 6) DEFAULT 'NULL', CHANGE balance balance NUMERIC(20, 6
6wkzu    ) DEFAULT 'NULL')
6wkzu  
6wkzu  
6wkzu  In Exception.php line 18:
6wkzu  
6wkzu    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
6wkzu    ue for 'adjustment'
6wkzu  
6wkzu  
6wkzu  In PDOStatement.php line 115:
6wkzu  
6wkzu    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val
6wkzu    ue for 'adjustment'
6wkzu  
6wkzu  

```

**Step 6**

```
public:
total 12861
drwxr-xr-x 10 1500 1500    4096 Mar 30 16:43 .
drwxr-xr-x  4 root root    4096 Mar 30 16:48 ..
drwxrwxr-x  6 1500 1500    4096 Mar 28 11:52 assets
drwxrwxr-x  2 1500 1500    4096 Mar 28 11:54 css
-rwxrwxr-x  1 1500 1500   15086 Mar 26 04:27 favicon.ico
-rwxrwxr-x  1 1500 1500    2700 Mar 26 04:27 favicon.png
-rwxrwxr-x  1 1500 1500    8120 Mar 26 04:27 flutter_service_worker.js
drwxrwxr-x  2 1500 1500    4096 Mar 28 11:52 icons
drwxrwxr-x  3 1500 1500    4096 Mar 28 11:52 images
-rwxrwxr-x  1 1500 1500    1850 Mar 26 04:27 index.php
drwxrwxr-x  5 1500 1500    4096 Mar 28 11:52 js
drwxr-xr-x  2 1500 1500    4096 Mar 28 11:52 logo
-rwxrwxr-x  1 1500 1500 7993886 Mar 26 04:27 main.dart.js
-rwxrwxr-x  1 1500 1500 5100101 Mar 26 04:27 main.dart.js.map
-rwxrwxr-x  1 1500 1500     708 Mar 26 04:27 manifest.json
-rwxrwxr-x  1 1500 1500    1941 Mar 28 11:54 mix-manifest.json
-rwxrwxr-x  1 1500 1500      24 Mar 26 04:27 robots.txt
drwxrwxr-x  2 1500 1500    4096 Mar 28 11:52 svg
drwxrwxr-x  4 1500 1500    4096 Mar 28 11:52 vendor
-rw-r--r--  1 1500 1500       7 Mar 30 16:43 version
-rwxrwxr-x  1 1500 1500      74 Mar 26 04:27 version.json

storage:
total 20
drwxrwxrwx 5 1500 1500 4096 Mar 30 16:43 .
drwxr-xr-x 4 root root 4096 Mar 30 16:48 ..
drwxrwxr-x 2 1500 1500 4096 Mar 28 11:52 app
drwxrwxr-x 6 1500 1500 4096 Mar 28 11:52 framework
drwxrwxr-x 2 1500 1500 4096 Mar 28 11:52 logs

```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Edit**

```
    Server: maxscale via TCP/IP
    Server type: MariaDB
    Server version: 10.3.28-MariaDB-1:10.3.28+maria~focal - mariadb.org binary distribution
    Protocol version: 10
    User: root@10.0.13.124
    Server charset: cp1252 West European (latin1)
```

full Server variables and settings

https://ibb.co/xJnH5kc
