### ISSUE TITLE
Docker logs spammed with "coudn't exec shutdown.sh", "child process was not spawned"

### ISSUE THREAD

**Issue by AleksaDjordjic** [invoiceninja/dockerfiles#318]
**Setup information**
docker-compose

**Describe the bug**
Docker log is spammed (messages non-stop every second) about "supervisor: couldn't exec shutdown.sh", then "child process was not spammed" and some other info logs. Over and over again

**To reproduce**
Update Invoice Ninja from 5.1.27 to 5.1.34
Standard update:
docker-compose down
docker-compose pull
docker-compose up -d

**Expected behavior**
Docker logs are clean, requests are logged etc.

**Screenshots/logs**
![image](https://user-images.githubusercontent.com/33227154/113699038-5e58a400-96d5-11eb-91fa-7bdde8ea224b.png)

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Additional context**
Was told to post this issue here after reporting a 500 Server Error when processing payments: [Forum post](https://forum.invoiceninja.com/t/500-server-error-when-processing-payments/6565/10)

**Comment by lwj5** [comment]
Can you post your whole docker-compose.yml here. Please remove any sensitive info.

And have you read https://github.com/invoiceninja/dockerfiles#updating-the-image-when-using-docker-compose ?

**Comment by AleksaDjordjic** [comment]
> Can you post your whole docker-compose.yml here. Please remove any sensitive info.
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    #ports:
      #- "8005:80"
      #- "443:443"
    networks:
      - invoiceninja
      - main_main-network
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/shutdown.sh:/usr/local/bin/shutdown.sh
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  db:
    image: mysql:5
#    For auto DB backups comment out image and use the build block below
#    build:
#      context: ./config/mysql
    #ports:
    #  - "3305:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

      # remove comments for next 4 lines if you want auto sql backups
      #- ./docker/mysql/bak:/backups:rw
      #- ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      #- ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      #- ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
  # cron:
  #   image: invoiceninja/invoiceninja:alpine-4
  #   volumes:
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
      # - ./docker/app/public/logo:/var/www/app/public/logo:rw,delegated
  #   entrypoint: |
  #     /bin/sh -c 'sh -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja
  #

networks:
  main_main-network:
    external: true
  invoiceninja:
```

> And have you read https://github.com/invoiceninja/dockerfiles#updating-the-image-when-using-docker-compose ?
Ah, no I didn't, this was the first time I updated it so just followed what I found on the UI itself.

Tried `git pull` now and got:
```
error: Your local changes to the following files would be overwritten by merge:
        .github/ISSUE_TEMPLATE/bug_report.md
        .github/workflows/build_push.yml
        Makefile
        README.md
        alpine/Dockerfile
        alpine/Dockerfile_v5
        config/mysql/Dockerfile
        config/php/php.ini
        config/shutdown.sh
        config/supervisor/supervisord.conf
        docker-compose.yml
        env
```

Although I didn't change any of those files, only the env and docker-compose.yml.
I'm not quite experienced with `git cli`, only used GitHub Desktop, not sure how to resolve this.
