### ISSUE TITLE
(helm) can't configure APP_URL to use https

### ISSUE THREAD

**Issue by sleeyax** [invoiceninja/dockerfiles#343]
Currently the `APP_URL` config value assumes the configured host communicates over plain HTTP:

https://github.com/invoiceninja/dockerfiles/blob/8e9e7c47da71e2979c214777020cf0e3f3c8c4b7/charts/invoiceninja/templates/configmap.yaml#L15-L19

Because of security reasons I'd prefer to use HTTPS though, so are there any plans to support this?

Maybe allow the programmer to configure the full URL instead (and not just the host)? For example:
```yaml
data:
  {{- if .Values.nginx.ingress.enabled }}
  APP_URL: "{{ .Values.nginx.ingress.url}}"
  {{- else }}
  # ...
```
