### ISSUE TITLE
company logos not working

### ISSUE THREAD

**Issue by jxsl13** [invoiceninja/dockerfiles#364]
My setup
```yaml
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    ports:
      - "127.0.0.1:9080:80"
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw
    depends_on:
      - db
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  db:
    image: mysql:5
    ports:
      - "127.0.0.1:3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

      # remove comments for next 4 lines if you want auto sql backups
      - ./docker/mysql/bak:/backups:rw
      #- ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      - ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      - ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip


networks:
  invoiceninja:
```
When I try to upload a png logo, it seems to have been uploaded successfully, but also fails to render everywhere.
Neither on the example invoice, nor anywhere else.

According to this thread, I'd guess that the docker images might need to have those dependencies installed when building:
https://forum.invoiceninja.com/t/cannot-upload-logo-self-hosted/2635/2
