### ISSUE TITLE
Cannot use named volumes for `/var/www/app/public`

### ISSUE THREAD

**Issue by zaxbux** [invoiceninja/dockerfiles#373]
**Setup information**
docker-compose

**Describe the bug**
The current Dockerfile for v5 does not create the `/var/www/app/public` directory, preventing use of named volumes at runtime.

See: https://github.com/docker/compose/issues/3270#issuecomment-543603959

**To reproduce**

docker-compose.yaml
```yaml
volumes:
  invoiceninja_storage:
  invoiceninja_public:

services:
  server:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - "invoiceninja_public:/var/www/app/public:ro"

  app:
    image: invoiceninja/invoiceninja:5
    volumes:
      - "invoiceninja_public:/var/www/app/public:rw,delegated"
      - "invoiceninja_storage:/var/www/app/storage:rw,delegated"
    depends_on:
      - db

# db service, etc...
```

**Expected behavior**
The `/var/www/app/public` directory should be created during build, e.g.:

```dockerfile
...

RUN mkdir /var/www/app/public && chown -R $UID:$UID /var/www/app/public

USER $UID

...
```

Currently, it looks like that directory is moved during build and then re-created during runtime.

**Screenshots/logs**

On `docker-compose up`:

```
Recreating invoiceninja-v5_1 ... done
Attaching to invoiceninja-v5_1
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/assets': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/css': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/favicon.ico': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/favicon.png': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/flutter_service_worker.js': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/icons': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/images': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/index.php': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/js': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/logo': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/main.dart.js': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/main.dart.js.map': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/main.foss.dart.js': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/main.foss.dart.js.map': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/main.wasm.dart.js': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/manifest.json': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/mix-manifest.json': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/robots.txt': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/svg': Permission denied
invoiceninja-v5_1        | cp: can't create directory '/var/www/app/public/vendor': Permission denied
invoiceninja-v5_1        | cp: can't create '/var/www/app/public/version.json': Permission denied
```

**Docker**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**
