### ISSUE TITLE
Freshly configured docker-compose setup: [ERROR] [Entrypoint]: Error connecting to DB app_1  

### ISSUE THREAD

**Issue by vogelfreiheit** [invoiceninja/dockerfiles#400]
**Setup information**
docker-compose

The env file (sanitized):

```
APP_URL=https://xxx
APP_KEY="base64:xxx"
APP_DEBUG=true
REQUIRE_HTTPS=true
PHANTOMJS_PDF_GENERATION=false
PDF_GENERATOR=snappdf
QUEUE_CONNECTION=database

MAIL_HOST=xxx
MAIL_USERNAME=xxx
MAIL_PASSWORD=xxx
MAIL_DRIVER=smtp
MAIL_FROM_ADDRESS=xxx
TRUSTED_PROXIES="*"

MYSQL_DATABASE=ninja
MYSQL_ROOT_PASSWORD=xxx
MYSQL_USER=ninja
MYSQL_PASSWORD=xxx

DB_USERNAME=ninja
DB_PASSWORD=xxx
DB_DATABASE=ninja
DB_HOST=db
DB_PORT=3306
DB_USERNAME1=ninja
DB_PASSWORD1=xxx
DB_DATABASE1=ninja
DB_HOST1=db
DB_PORT1=3306
```

The docker compose file (sanitized):

```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "127.0.0.1:xxx:80"
      #- "443:443"
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  app:
#    image: invoiceninja/invoiceninja:5
    build:
      context: ./app-build/
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  db:
    build:
      context: ./config/mysql
    ports:
      - "127.0.0.1:xxx:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
      - ./docker/mysql/bak:/backups:rw
      - ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

networks:
  invoiceninja:
```

The custom invoiceninja image only has the following in the Dockerfile, everything else is inherited as-is from original:

```
FROM invoiceninja/invoiceninja:5

USER root

COPY fixattrs.sh /
RUN chmod 755 /*.sh

RUN chmod g-w /usr/local/bin
RUN chmod g-w /usr/local
RUN chmod g-w /usr
```

The only thing it does is remove g+w from the directories where that should not be present for security reasons.

**Describe the bug**

The fresh installation is unable to launch the app container and it seems the DB connection is not operating.

**To reproduce**
Steps to reproduce the behavior: following the official instructions with the provided files.

**Expected behavior**

A working setup to migrate.

**Screenshots/logs**
```
app_1     | 2021-09-30T15:45:36Z [ERROR] [Entrypoint]: Error connecting to DB
app_1     | 2021-09-30T15:46:36Z [INFO] [Entrypoint]: Initialising Invoice Ninja...
```
