### ISSUE TITLE
Missing MYSQL options from example env file

### ISSUE THREAD

**Issue by moorsey** [invoiceninja/dockerfiles#447]
**Setup information**

docker-compose

**Describe the bug**
Example docker-compose has missing MYSQL options, the container complains about missing MYSQL password options on start, see logs below.  Once an option is added, errors are still shown such as:

`
2022-06-15T14:42:10.993421Z 49 [Note] Access denied for user 'ninja'@'172.26.0.4' (using password: YES)`

**To reproduce**
Start with the default docker-compose and env file to see the errors

**Expected behavior**
Default compose file should have all required options included.  Adding "MYSQL_ROOT_PASSWORD" option to the env file fixes this issue

**Screenshots/logs**

```
db_1      | 2022-06-15 14:22:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.38-1debian10 started.
db_1      | 2022-06-15 14:22:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1      | 2022-06-15 14:22:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.38-1debian10 started.
db_1      | 2022-06-15 14:22:04+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
db_1      |     You need to specify one of the following:
db_1      |     - MYSQL_ROOT_PASSWORD
db_1      |     - MYSQL_ALLOW_EMPTY_PASSWORD
db_1      |     - MYSQL_RANDOM_ROOT_PASSWORD
```

**Docker**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:44 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**docker-compose.yml**

Mostly defaults, few edits to access via nginx-proxy-manager

env file as is, other than editing the URL, secret key and adding "MYSQL_ROOT_PASSWORD=ninja" variable.

Also edited "DB_HOST" value to "invoiceninja_db_1", to match.  I am thinking it is possible that as I am not using my host IP address, but access all through reverse proxy, my removing the "extra_hosts" option is causing issues, but as IPs are allocated randomly when a container starts, I can't define anything here

```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    #ports:
    #  - "80:80"
      #- "443:443"
    networks:
      - invoiceninja
      - proxy
    #extra_hosts:
    #  - "in5.localhost:192.168.0.124 " #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja
    #extra_hosts:
    #  - "in5.localhost:192.168.0.124 " #host and ip

  db:
    image: mysql:5
    ports:
      - "3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

      # remove comments for next 4 lines if you want auto sql backups
      - ./docker/mysql/bak:/backups:rw
      - ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      - ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      - ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja
    #extra_hosts:
    #  - "in5.localhost:192.168.0.124 " #host and ip

networks:
  invoiceninja:
  proxy:
   external: true
```
