### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'scheduled_run' 

### ISSUE THREAD

**Issue by fbc** [invoiceninja/dockerfiles#448]
I've already checked on stack overflow and here. There does not appear to be a solution that I can apply to my docker-compose file.

**Setup information**
docker-compose with mariadb

```
version: '3.7'

services:
  invoiceninja:
    image: invoiceninja/invoiceninja
    restart: always
    volumes:
      #- ./config/hosts:/etc/hosts:ro
      - /home/x/my/public:/var/app/public
      - /home/x/my/storage:/var/app/storage
    environment:
      - APP_ENV='production'
      - APP_DEBUG=0
      - APP_URL='https://x'
      - APP_KEY='base64:/x='
      - APP_CIPHER='AES-256-CBC'
      - DB_TYPE='mysql'
      - DB_STRICT='true'
      - DB_HOST='mariadb'
      - DB_DATABASE='invoiceninja'
      - DB_USERNAME='invoiceninja'
      - DB_PASSWORD='x!'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.invoiceninja.entrypoints=websecure"
      - "traefik.http.routers.invoiceninja.rule=Host(`x`)"
      - "traefik.http.routers.invoiceninja.tls=true"
      - "traefik.http.routers.invoiceninja.tls.options=default"
      - "traefik.http.routers.invoiceninja.tls.certresolver=lets-encrypt"
      #- "traefik.http.services.invoiceninja.loadbalancer.server.port=9000"
    networks:
      - web
      - db
networks:
  web:
    external: true
  db:
    external: true
```
mariadb compose file

```
version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=x
    networks:
      - db
networks:
  db:
    external: true
```

**Describe the bug**
log fills with this error and container restarts, this cycle repeats over and over again.

**To reproduce**
Start these containers up and see if you can make them work I suppose.

**Expected behavior**
I expected the app to startup

**Screenshots/logs**

```
yup I pasted above.
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Docker version 20.10.16, build aa7e414
```

**Additional context**
I've tried toggling strict mode. but it does not help.
