### ISSUE TITLE
Custom SMTP don't seem to work

### ISSUE THREAD

**Issue by wrender** [invoiceninja/dockerfiles#459]
**Setup information**

Helm

**Describe the bug**
When I try to apply custom environments in my values.yaml file they don't seem to take affect.  I exec into the kubernetes invoiceninja pod, and cat the .env file, and I don't see the smtp settings in affect after.  Am I missing something? Basically just trying to relay emails through an Office 365 account.
```
extraEnvVars:
  - name: MAIL_HOST
    value: "smtp.office365.com"
  - name: MAIL_PORT
    value: "587"
  - name: MAIL_USERNAME
    value: "wes@mydomain.com"
  - name: MAIL_PASSWORD
    value: "mystrongpassword"
  - name: MAIL_ENCRYPTION
    value: "TLS"
  - name: MAIL_FROM_ADDRESS
    value: "wes@mydomain.com"
  - name: MAIL_FROM_NAME
    value: "Wes"
```

**Expected behavior**
I would expect the .env file in the pod to reflect the settings I put in extraEnvVars.
