### ISSUE TITLE
Error 500 Undefined property $valid_until 

### ISSUE THREAD

**Issue by mfeddani** [invoiceninja/dockerfiles#469]
**Setup information**
docker-compose : 
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    #env_file: env
    volumes:
      # Vhost configuration
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./config/app/public:/var/www/app/public:ro
    depends_on:
      - app
    networks:
      - traefik-public
      - ninja
    extra_hosts:
      - "saas:51.210.249.58" #host and ip
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.xxxx.service=xxxxx"
      - "traefik.http.services.xxxx.loadbalancer.server.port=80"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.xxxx.rule=Host(XXXX`)"
      - "traefik.http.routers.xxxx.middlewares=https-redirect@docker"
      - "traefik.http.routers.xxxx.entrypoints=https"
      - "traefik.http.routers.xxxx.tls=true"
      - "traefik.http.routers.xxxx.tls.certresolver=xxxxx"

  app:
    image: invoiceninja/invoiceninja:5
    #env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./configshutdown.sh:/usr/local/bin/shutdown.sh
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks: 
      - ninja  
    extra_hosts:
      - "xxxx:xxxx" #host and ip
    environment:
      - PUID=1500
      - PGID=1500
      - APP_ENV='production'
      - APP_URL=https://xxxxxxx
      - APP_KEY=xxxxxxxx 
      - APP_DEBUG=false
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_USERNAME1=ninja1_xxxx
      - DB_PASSWORD1=xxxxxxx
      - DB_DATABASE1=xxxxxxxx
      - APP_CIPHER=AES-256-CBC
      - SESSION_ENCRYPT=true
      - SESSION_SECURE=true
      # BEHIND TRAEFIK
      - VIRTUAL_HOST=xxxxxxxx
      - LETSENCRYPT_HOST=xxxxxxx
      - LETSENCRYPT_EMAIL=xxxxxxxxx
      - TRUSTED_PROXIES='xxxxxx/28,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      # SMTP
      - MAIL_HOST=xxxxx
      - MAIL_USERNAME=xxxx
      - MAIL_PASSWORD=xxxxx
      - MAIL_DRIVER=smtp
      - MAIL_FROM_NAME=xxxxx
      - MAIL_FROM_ADDRESS=xxxxxx
      - MAIL_ENCRYPTION=tls
      - MAIL_PORT='587'
      # this is a system variable please do not remove
      - IS_DOCKER=true

  db:
    image: mariadb:10.3
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_USER=ninja1_xxxx
      - MYSQL_PASSWORD=xxxxxx
      - MYSQL_DATABASE=xxxxxx
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - g2cninja
    extra_hosts:
      - "xxxxxx:xxxxx" #host and ip  

networks:
  traefik-public:
    external: true
  ninja:
```

**Describe the bug**
I have an `500: Server Error `

**Expected behavior**
When I want to enable 'join PDF' in email parameters, I have `500: Server Error ` when I click on green button `save`
Same issue I want to change language, when I click on green button `save`

**Screenshots/logs**
```
production.ERROR: Undefined property: stdClass::$valid_until {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$valid_until at /var/www/app/app/Utils/Traits/SettingsSaver.php:55)
```

<img width="948" alt="image" src="https://user-images.githubusercontent.com/111126740/198579744-9281df3b-e9f5-40aa-a8b6-ece63d8c1ab7.png">

```
production.ERROR: Undefined property: stdClass::$valid_until {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$valid_until at /var/www/app/app/Utils/Traits/SettingsSaver.php:55)
[stacktrace]
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/app/app/Utils/Traits/SettingsSaver.php(55): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/app/app/Http/ValidationRules/ValidSettingsRule.php(33): App\\Http\\ValidationRules\\ValidSettingsRule->validateSettings()
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(814): App\\Http\\ValidationRules\\ValidSettingsRule->passes()
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(605): Illuminate\\Validation\\Validator->validateUsingCustomRule()
#5 /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(417): Illuminate\\Validation\\Validator->validateAttribute()
#6 /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(448): Illuminate\\Validation\\Validator->passes()
#7 /var/www/app/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(31): Illuminate\\Validation\\Validator->fails()
#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1267): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1232): Illuminate\\Container\\Container->fireCallbackArray()
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1217): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\\Container\\Container->fireResolvingCallbacks()
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\\Container\\Container->resolve()
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\\Container\\Container->make()
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(85): Illuminate\\Foundation\\Application->make()
#17 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(50): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
#18 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(30): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
#19 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(60): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
#20 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(40): Illuminate\\Routing\\ControllerDispatcher->resolveParameters()
#21 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#22 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#23 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#24 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#25 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(62): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#27 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#28 /var/www/app/app/Http/Middleware/QueryLogging.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\QueryLogging->handle()
#30 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#32 /var/www/app/app/Http/Middleware/Locale.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Locale->handle()
#34 /var/www/app/app/Http/Middleware/TokenAuth.php(96): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\TokenAuth->handle()
#36 /var/www/app/app/Http/Middleware/SetDb.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SetDb->handle()
#38 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/app/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#47 /var/www/app/app/Http/Middleware/Cors.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Cors->handle()
#49 /var/www/app/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#51 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#59 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /var/www/app/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 {main}
"}
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Additional context**
I have had this problem since I updated to the latest version 

docker-compose down
docker-compose pull
docker-compose up -d

Current version : v5.5.34-C99
