### ISSUE TITLE
XMLHttpRequest error when requesting PDF files - after migrating between servers

### ISSUE THREAD

**Issue by mmaeffert** [invoiceninja/dockerfiles#530]
### How I migrated

- using [these ](https://github.com/invoiceninja/dockerfiles)files
- transfering these volumes via rsync

> dockerfiles/docker/app/public
> dockerfiles/docker/app/storage
> dockerfiles/config/hosts

- using this docker-compose.yml
```
version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    ports:
      - "8001:80"
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini

    depends_on:
      - db
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip
  db:
    image: mariadb:10.4
    ports:
      - "3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

networks:
  invoiceninja:
```

- Using this env file:
``` 
# IN application vars
APP_URL=http://placeholder.de
APP_KEY=xxxxxxx
APP_DEBUG=true
REQUIRE_HTTPS=false
PHANTOMJS_PDF_GENERATION=true
PDF_GENERATOR=snappdf
TRUSTED_PROXIES='*'


QUEUE_CONNECTION=database
...
``` 

- Had to switch from mysql to mariadb due to change in architecture
- Created database dump of old installation
- Manually pushed the dump into the new database

### My issue
When requesting invoices (either those created on old installation and the new installation), I get the error "XMLHttpRequest error.". It does not matter whether I want to access this via the customer portal, when trying to send the email or just viewing the invoice. 

I have tried:
- Different browsers
- `php artisan cache:clear`
- Rebuilt
- Restart
- New domain

## Error messages from browser console
The orange line is where I press "Show PDF"
The IP 10.0.0.1:8001 is the apps file inside my VPN

![tmppp](https://github.com/invoiceninja/dockerfiles/assets/100378374/84935671-1326-4b32-9953-5e93383b0fa3)
![image](https://github.com/invoiceninja/dockerfiles/assets/100378374/46e2bc79-c95d-4ca0-bae4-3e70b4c305ae)

Looking into the app container console, I get no error messages.
