### ISSUE TITLE
Connection reset by peer error with docker install 

### ISSUE THREAD

**Issue by grozandrei** [invoiceninja/dockerfiles#543]
## Describe the bug

A fresh install using docker-compose is not working.

### Steps To Reproduce

Have the following docker-compose file content (I have another nginx in place which is a reverse proxy - that's what **VIRTUAL_HOST** and **VIRTUAL_PORT** env vars are used for):

```
version: '3.8'
services:
  invoiceninja:
    image: invoiceninja/invoiceninja:5.7.24
    restart: unless-stopped
    expose:
      - 9000
    environment:
      - VIRTUAL_HOST=invoice.mydomain.lcl
      - VIRTUAL_PORT=9000
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=http://mydomain.mydomain.lcl
      - APP_KEY=base64:U+y2gftQHUfs1n3P2brAd/rWFkPztgbMK76sjGkqb7c=
      - APP_CIPHER=AES-256-CBC
      - TRUSTED_PROXIES=*
      - REQUIRE_HTTPS=false
      - IS_DOCKER=true
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=invoiceninja
      - DB_USERNAME=invoiceninja
      - DB_PASSWORD=password
    volumes:
      - invoiceninja-public:/var/www/app/public
      - invoiceninja-storage:/var/www/app/storage
    networks:
      - invoice
      - proxy
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=invoiceninja
      - MARIADB_USER=invoiceninja
      - MARIADB_PASSWORD=password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - invoice
volumes:
  invoiceninja-public:
    driver: local
  invoiceninja-storage:
    driver: local
  mariadb:
    driver: local
networks:
  invoice: {}
  proxy:
    external: true
```

### Expected Behavior

The app should respond properly to http requests.

### Logs

```
~ $ curl localhost:9000
curl: (56) Recv failure: Connection reset by peer
