### ISSUE TITLE
Container startup only works with bind mount; `cp: can't create directory '/var/www/app/storage/app': Permission denied`

### ISSUE THREAD

**Issue by ToshY** [invoiceninja/dockerfiles#558]
**Setup information**

docker compose v2.24.0

**Describe the bug**

It's not possible to setup the application using docker volumes with the example config provided, as it throws the following error in the container logging:

```txt
invoiceninja-1   | 2024-01-17T17:48:47.208852859Z cp: can't create directory '/var/www/app/storage/app': Permission denied
invoiceninja-1   | 2024-01-17T17:48:48.206288663Z cp: can't create directory '/var/www/app/storage/app': Permission denied
invoiceninja-1 exited with code 1
```

This is similar to #330 , but because I'm not using bind mount but volumes I cannot perform `chmod / chown` operations, as the volumes are manager by docker.

**To reproduce**
1. Use fresh [`docker-compose.yml`](https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose.yml) (or something similar)
2. For the app service change the following volumes.

from
```yml
services:
  app:
    volumes:
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
```
to
```yml
services:
  app:
    volumes:
      - app_public:/var/www/app/public:rw,delegated
      - app_storage:/var/www/app/storage:rw,delegated

volumes:
  app_public:
    driver: local
  app_storage:
    driver: local
```

3. Up the services.
4. Check logging of app container throwing the error.

Also tried using `user: root` and `user: 1500` on app service, which both result in similar error in UI.

![image](https://github.com/invoiceninja/dockerfiles/assets/31921460/0a3aa67b-8aba-4505-9114-9c180aa55a15)

**Expected behavior**

Able to use volumes instead of bind mounts.

**Docker**:
- Output of `docker version`:
```txt
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**
`invoiceninja/invoiceninja`: `5.8.10`
