### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by MaximeWillinger** [invoiceninja/dockerfiles#56]
I'm using this docker image in combination with jwilder/nginx-proxy. Everything looks good but when I try to submit the install form, I get a 500 error.

The only error I get in the logs is `Debugbar exception: A non well formed numeric value encountered [] []`.

I tried a `composer update` but it didn't solve the issue.

Do you have any idea?

**laravel-error.log:**
```bash
[2017-08-31 23:11:28] production.ERROR: Debugbar exception: A non well formed numeric value encountered [] []
```

**docker-compose.yml:**
```
version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ninja
      MYSQL_ROOT_PASSWORD: pwd

  app:
    image: invoiceninja/invoiceninja
    links:
      - db:mysql
    env_file: .env
    networks:
      - nginx-proxy
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app:app
    ports:
      - 8082:80
    environment:
      VIRTUAL_HOST: invoices.mydomain.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

**nginx.conf:**
```
user www-data;

events {
  worker_connections 768;
}

http {
    upstream backend {
        server app:9000;
    }
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;
    gzip_disable "msie6";

    server {
        listen      80 default;
        server_name your_ininja_site;

        root /var/www/app/public;

        index index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        sendfile off;

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass backend;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_intercept_errors off;
            fastcgi_buffer_size 16k;
            fastcgi_buffers 4 16k;
	    fastcgi_param HTTPS 1;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
```

**.env:**
```
APP_DEBUG=1
APP_URL=https://invoices.mydomain.com
DB_USERNAME=root
DB_PASSWORD=pwd
DB_HOST=mysql
MAIL_HOST=mail.service.host
MAIL_USERNAME=username
MAIL_PASSWORD=password
MAIL_DRIVER=smtp
MAIL_FROM_NAME="My name"
MAIL_FROM_ADDRESS=user@mail.com
TRUSTED_PROXIES='10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
```
