### ISSUE TITLE
(helm chart) Mixed content HTTP/HTTPS behind reverse proxy

### ISSUE THREAD

**Issue by cianiandreadev** [invoiceninja/dockerfiles#720]
Hi All,

I deployed Invoice Ninja using the main [helm chart](https://artifacthub.io/packages/helm/invoiceninja/invoiceninja) and was working correctly until, probably, I uploaded some content (probably the company logo?) that completely broke the system.

Now on the browser I see the following error:

```
[Warning] [blocked] The page at https://mywesite.example/ requested insecure content from http://mywebsite.example/js/pdf.min.js. This content was blocked and must be served over HTTPS.

[Error] ReferenceError: Can't find variable: pdfjsLib
	Global Code (mywebsite.example:12)
[Debug] Flutter Web Bootstrap: Auto. (main.foss.dart.js, line 9287)
[Error] Failed to load resource: the server responded with a status of 404 () (canvaskit.js, line 0)
```

[I saw a similar old related issue](https://github.com/invoiceninja/dockerfiles/issues/343#issuecomment-2636460403) but is old and closed while the problem seems to persist.

To keep in mind that I do SSL termination on AWS cloudfront, therefore communication from K8s services and reverse proxy are in HTTP:80.

This is the overview setup:

InvoiceNinja (http) <--> (http) traefik (http) <--> (http) AWS (https) <-> End user

I did already tried:

1. To specify the `APP_URL` to use https in the `values.yml` (https://mywebsite.example)
2. To set the `trustedProxies`, both to the traefik ip, as well as `*`
3. Set `requireHttps` to `true` in the values.yml

What else could be the problem? I don't quite understand.

Following, my values.yml configuration

```yml

image:
  tag: 5.6.24

appURL: "https://mywebsite.example" # Before was just "mywebsite.example"

userEmail: "myemail@bla.com"

trustedProxies: "10.0.0.6" # or '*', both don't work
requireHttps: true # no impact

existingSecret: "secret-invoiceninja"

fullnameOverride: "invoiceninja"

ingress:
  ingressClassName: traefik
  hostname: mywebsite.example

persistence:
  public:
    enabled: true
    storageClass: "longhorn"
    existingClaim: pvc-invoiceninja
    size: 5Gi

```

Thanks for your support.

**Expected behavior**
The system should work behind a reverse proxy that provides SSL termination.
