### ISSUE TITLE
Rootless podman permissions issue

### ISSUE THREAD

**Issue by den5o** [invoiceninja/dockerfiles#724]
This is related to https://github.com/invoiceninja/dockerfiles/issues/512#issue-1698970264 however the suggested solution doesn't work for me and is slightly different as I'm using podman volumes to get around SELinux woes.

First, this is the compose file I'm using:
```
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file

services:
  app:
    image: docker.io/invoiceninja/invoiceninja-debian:5.11
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.env:/var/www/html/.env
      - app_cache:/var/www/html/bootstrap/cache
      - app_public:/var/www/html/public
      - app_storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging: *default-logging

  nginx:
    image: docker.io/nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - app_public:/var/www/html/public:ro
      - app_storage:/var/www/html/storage:ro
    networks:
      - app-network
    depends_on:
      - app
    logging: *default-logging

  mysql:
    image: docker.io/mysql:8
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

  redis:
    image: docker.io/redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

networks:
  app-network:
    driver: bridge

volumes:
  app_cache:
    driver: local
  app_public:
    driver: local
  app_storage:
    driver: local  
  mysql_data:
    driver: local
  redis_data:
    driver: local
```

Deploying the stack without any volumes present on the host works fine the first time and is accessible through a browser. Taking it down and up again results in permission errors in `/var/www/html/public`. Specifically `rm: cannot remove '/var/www/html/public/filename': Permission denied`

Using `userns_mode: keep-id:uid=1500` in the app section of the compose file results in `Error: --userns and --pod cannot be set together`. Using podman compose always creates a pod so that's a non starter.

Using `podman compose --pod-args '--userns keep-id' up -d` results in `depends_on:` failing to find the container it's looking for.

What I tried next was to remove the app section from the compose file and launch it separately using podman run:

```
podman run \
    --network-alias=app \
    --restart=unless-stopped \
    --userns=keep-id:uid=1500 \
    --env-file=/opt/apps/invoiceninja/.env \
    -v=/opt/apps/invoiceninja/.env:/var/www/html/.env \
    -v=invoiceninja_app_cache:/var/www/html/bootstrap/cache \
    -v=invoiceninja_app_public:/var/www/html/public \
    -v=invoiceninja_app_storage:/var/www/html/storage \
    --network invoiceninja_app-network \
    docker.io/invoiceninja/invoiceninja-debian:5.11
```

For some reason this doesn't always work without volumes present. It only worked once in the 8 or so times I tried it. However the one time it did work, the permission errors returned the second time I launched it.

I'm using ansible to deploy all my services as well as using it for my backup strategy. My workaround for this that seems to work flawlessly every time is to purge all volumes except `mysql_data` before deploying the stack. This is easy to do with ansible however it's an issue every time the host is restarted.

Is this safe? What also slightly worries me is it could stop working in the future. How likely is that?

I'd hate to become too invested in this admittedly great app and one day this stops being a feasible workaround. I think worst case scenario would be that I'd have to stay pinned to the latest version of invoiceninja that this worked. Although not too bad, it's not ideal either.
