### ISSUE TITLE
Issue accessing app

### ISSUE THREAD

**Issue by ghxstxch** [invoiceninja/dockerfiles#747]
**Setup information**

docker-compose (via Dockge)

**Describe the bug**
I am trying to deploy invoiceninja via dockge (using docker-compose). The app does deploy successfully if done via CLI, but when ripping out the compose.yaml and .env and putting it in Dockge, the webui seems to be inaccessible. I realize this isn't a typical setup, but Dockge should be very similar to command-line dock-compose. Unsure what I'm doing wrong, but I would appreciate any guidance. 

**To reproduce**
1. Copy contents of compose.yaml to Dockge's compose.yaml section, same with .env file, edit as necessary 
2. Deploy 

**Expected behavior**
Accessing app via port 80

**Screenshots/logs**

```
invoiceninja-nginx-1  | 2025/04/05 15:52:18 [notice] 1#1: exit
invoiceninja-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
invoiceninja-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
invoiceninja-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
invoiceninja-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
invoiceninja-nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
invoiceninja-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
invoiceninja-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
invoiceninja-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: using the "epoll" event method
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: nginx/1.27.4
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0) 
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: OS: Linux 6.1.0-27-amd64
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: start worker processes
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: start worker process 20
invoiceninja-nginx-1  | 2025/04/05 15:55:47 [notice] 1#1: start worker process 21
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  Caching framework bootstrap, configuration, and metadata.  
invoiceninja-app-1    | 
invoiceninja-app-1    |   config ........................................................ 50.45ms DONE
invoiceninja-app-1    |   events ......................................................... 3.15ms DONE
invoiceninja-app-1    |   routes ....................................................... 127.51ms DONE
invoiceninja-app-1    |   views ........................................................ 336.82ms DONE
invoiceninja-app-1    | 
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  Discovering packages.  
invoiceninja-app-1    | 
invoiceninja-app-1    |   babenkoivan/elastic-client ............................................ DONE
invoiceninja-app-1    |   babenkoivan/elastic-scout-driver ...................................... DONE
invoiceninja-app-1    |   imdhemy/laravel-purchases ............................................. DONE
invoiceninja-app-1    |   intervention/image .................................................... DONE
invoiceninja-app-1    |   invoiceninja/inspector ................................................ DONE
invoiceninja-app-1    |   laravel/octane ........................................................ DONE
invoiceninja-app-1    |   laravel/scout ......................................................... DONE
invoiceninja-app-1    |   laravel/slack-notification-channel .................................... DONE
invoiceninja-app-1    |   laravel/socialite ..................................................... DONE
invoiceninja-app-1    |   laravel/tinker ........................................................ DONE
invoiceninja-app-1    |   laravel/ui ............................................................ DONE
invoiceninja-app-1    |   livewire/livewire ..................................................... DONE
invoiceninja-app-1    |   nesbot/carbon ......................................................... DONE
invoiceninja-app-1    |   nunomaduro/termwind ................................................... DONE
invoiceninja-app-1    |   nwidart/laravel-modules ............................................... DONE
invoiceninja-app-1    |   sentry/sentry-laravel ................................................. DONE
invoiceninja-app-1    |   socialiteproviders/manager ............................................ DONE
invoiceninja-app-1    |   turbo124/beacon ....................................................... DONE
invoiceninja-app-1    | 
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  Nothing to migrate.  
invoiceninja-app-1    | 
invoiceninja-app-1    | Production setup completed
invoiceninja-app-1    | Starting supervisord...
invoiceninja-app-1    | 2025-04-05 15:56:16,922 INFO Set uid to user 0 succeeded
invoiceninja-app-1    | 2025-04-05 15:56:16,924 INFO supervisord started with pid 1
invoiceninja-app-1    | 2025-04-05 15:56:17,926 INFO spawned: 'php-fpm' with pid 532
invoiceninja-app-1    | 2025-04-05 15:56:17,928 INFO spawned: 'queue-worker_00' with pid 533
invoiceninja-app-1    | 2025-04-05 15:56:17,930 INFO spawned: 'queue-worker_01' with pid 534
invoiceninja-app-1    | 2025-04-05 15:56:17,933 INFO spawned: 'scheduler' with pid 535
invoiceninja-app-1    | 2025-04-05 15:56:18,935 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
invoiceninja-app-1    | 2025-04-05 15:56:18,936 INFO success: queue-worker_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
invoiceninja-app-1    | 2025-04-05 15:56:18,937 INFO success: queue-worker_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
invoiceninja-app-1    | 2025-04-05 15:56:18,937 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
invoiceninja-app-1    | [05-Apr-2025 15:56:36] NOTICE: fpm is running, pid 532
invoiceninja-app-1    | [05-Apr-2025 15:56:36] NOTICE: ready to handle connections
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  Running scheduled tasks.  
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  No scheduled commands are ready to run.  
invoiceninja-app-1    | 
invoiceninja-app-1    |    INFO  No scheduled commands are ready to run.  
invoiceninja-app-1    | 

```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.23
  GitCommit:        57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

Please let me know what other information I can provide to assist in figuring out what I've done wrong. Thanks!

**Comment by benbrummer** [comment]
Can you add your compose.yaml and .env without secrets to this issue?

**Comment by ghxstxch** [comment]
Absolutely! Here you go: 

compose.yaml:
```
x-logging: &a1
  options:
    max-size: 10m
    max-file: "3"
  driver: json-file
services:
  app:
    build:
      context: .
    image: invoiceninja/invoiceninja-debian:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      #- ${STRG_PATH}/.env:/var/www/html/.env
      - ${STRG_PATH}/app_public:/var/www/html/public
      - ${STRG_PATH}/app_storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging: *a1
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${STRG_PATH}/nginx:/etc/nginx/conf.d:ro
      - ${STRG_PATH}/app_public:/var/www/html/public:ro
      - ${STRG_PATH}/app_storage:/var/www/html/storage:ro
    networks:
      - app-network
    depends_on:
      - app
    logging: *a1
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${STRG_PATH}/mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u${MYSQL_USER}
        - -p${MYSQL_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *a1
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ${STRG_PATH}/redis_data:/data
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *a1
networks:
  app-network:
    driver: bridge
volumes:
  app_public:
    driver: local
  app_storage:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local

```


.env:

```
# IN application vars
APP_URL=http://10.0.20.101:8003
APP_KEY=@@@@@@@@@@@@@@@@@@@@@@@@@@@@
APP_ENV=production
APP_DEBUG=true
REQUIRE_HTTPS=false
PHANTOMJS_PDF_GENERATION=false
PDF_GENERATOR=snappdf
TRUSTED_PROXIES='*'


CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis

REDIS_HOST=redis
REDIS_PASSWORD=@@@@@@@@@@@@@@@@@@@@@@@
REDIS_PORT=6379

FILESYSTEM_DISK=debian_docker

# DB connection
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=ninja
DB_USERNAME=ninja
DB_PASSWORD=@@@@@@@@@@@@@@@@@@@
DB_ROOT_PASSWORD=@@@@@@@@@@@@@@@@@@@@@
DB_CONNECTION=mysql

# Create initial user
# Default to these values if empty
IN_USER_EMAIL=@@@@@@@@@@@
IN_PASSWORD=@@@@@@@@@@@@
# IN_USER_EMAIL=
# IN_PASSWORD=

# Mail options
MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS='@@@@@@@@@@'
MAIL_FROM_NAME='@@@@@@@@@@@'

# MySQL
MYSQL_ROOT_PASSWORD=@@@@@@@@@@@@@@@@@
MYSQL_USER=ninja
MYSQL_PASSWORD=@@@@@@@@@@@@@@@@@@
MYSQL_DATABASE=ninja

# GoCardless/Nordigen API key for banking integration
NORDIGEN_SECRET_ID=
NORDIGEN_SECRET_KEY=

IS_DOCKER=true
SCOUT_DRIVER=null
#SNAPPDF_CHROMIUM_PATH=/usr/bin/google-chrome-stable

```

**Comment by benbrummer** [comment]
Your `APP_URL=http://10.0.20.101:8003`, but your nginx is listening on 80, which url are you using in your browser? http://10.0.20.101:80?
Is there a reverse proxy inbetween?

**Comment by ghxstxch** [comment]
> Your `APP_URL=http://10.0.20.101:8003`, but your nginx is listening on 80, which url are you using in your browser? http://10.0.20.101:80?
> Is there a reverse proxy inbetween?
> 
> From your logs, the app is up and running, but nginx is not receiving any request.
> 
> 

So that was left there, my fault. I tried setting it to port 80 both for the app URL and nginx exposed port, and same with 8003. I couldn't connect to either.

**Comment by ghxstxch** [comment]
> As not a single request is reaching nginx something needs to be wrong with port mappings, ip or in the network. The app container looks fine.
> 
> Maybe it is related to [louislam/dockge#775](https://github.com/louislam/dockge/issues/775)

I think you may be right. I thought I had another service running successfully that also had an .env file, but I seem to have just listed the environment variable out into the compose.yaml like such: 
```
version: "3"
services:
  app:
    image: application:latest
    environment:
      ENV_VAR0: ${VARIABLE0}
      ENV_VAR1: ${VARIABLE1}
```
Dockge's .env seems to respect the path I have in the file - STRG_PATH= /path/to/data in my .env file, ${STRG_PATH} in the compose.yaml. - just not the in-app variables.

**Comment by ghxstxch** [comment]
Attempting what I mentioned above also doesn't seem to work, but I'm sure the error is still something I may have done.

Here is my new compose.yaml, with the .env variable baked in.

```
x-logging: &a1
  options:
    max-size: 10m
    max-file: "3"
  driver: json-file
services:
  app:
    #    build:
    #      context: .
    image: invoiceninja/invoiceninja:${TAG:-latest}
    restart: unless-stopped
    environment:
      - APP_URL=http://10.0.20.101:8003
      - APP_KEY=@@@@@@@@@@@@@
      - APP_ENV=production
      - APP_DEBUG=true
      - REQUIRE_HTTPS=false
      - PHANTOMJS_PDF_GENERATION=false
      - PDF_GENERATOR=snappdf
      - TRUSTED_PROXIES='*'
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - FILESYSTEM_DISK=debian_docker
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=@@@@@
      - DB_PASSWORD=@@@@@@
      - DB_ROOT_PASSWORD=@@@@@
      - DB_CONNECTION=mysql
      - IN_USER_EMAIL=@@@@@
      - IN_PASSWORD=@@@@@
      - MAIL_MAILER=log
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS='@@@@@'
      - MAIL_FROM_NAME='@@@@@@'
      - NORDIGEN_SECRET_ID=
      - NORDIGEN_SECRET_KEY=
      - IS_DOCKER=true
      - SCOUT_DRIVER=null
    volumes:
      #- .env:/var/www/html/.env
      - ${STRG_PATH}/app_public:/var/www/html/public
      - ${STRG_PATH}/app_storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging: *a1
    ports: []
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ${STRG_PATH}/nginx:/etc/nginx/conf.d:ro
      - ${STRG_PATH}/app_public:/var/www/html/public:ro
      - ${STRG_PATH}/app_storage:/var/www/html/storage:ro
    networks:
      - app-network
    depends_on:
      - app
    logging: *a1
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${STRG_PATH}/mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u${MYSQL_USER}
        - -p${MYSQL_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *a1
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ${STRG_PATH}/redis_data:/data
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *a1
networks:
  app-network:
    driver: bridge

#volumes:
#  app_public:
#    driver: local
#  app_storage:
#    driver: local
#  mysql_data:
#    driver: local
#  redis_data:
#    driver: local

```
