### ISSUE TITLE
Trouble adapting to docker-compose 3.6

### ISSUE THREAD

**Issue by Harti** [invoiceninja/dockerfiles#78]
I'm using a [reverse proxy](https://github.com/SteveLTN/https-portal) and require this installation to be on the same docker network, so I've got a certain syntax to add to my .yml files which isn't compatible with version 2.0 of docker-compose.
Therefore, I had to adapt the file. Since version 3 deprecated/dropped `volumes_from`, I'm not sure if I did everything right. Presumably not. I suggest you upgrade the file to something recent so that people can actually use it as-is.

docker-compose.yml
```
version: "3.6"

services:
  db:
    image: mysql:5
    env_file: .env
    restart: always
    volumes:
      - /home/invoiceninja-db/:/var/lib/mysql

  app:
    image: invoiceninja/invoiceninja
    depends_on:
      - db
    env_file: .env
    restart: always
    volumes:
      - /home/apps/invoiceninja/:/var/www/app:rw

  web:
    image: nginx:1
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/apps/invoiceninja/:/var/www/app:rw
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=invoice.example.com

  cron:
    image: invoiceninja/invoiceninja
    links:
      - db:mysql
    env_file: .env
    volumes:
      - /home/apps/invoiceninja/:/var/www/app:rw
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
              
networks:
    default:
        external:
            name: proxied
```

I opted against only mounting the storage folder and the logo into the container; I prefer to easily download a copy of everything via SFTP.

This seems to cause me issues as the app container keeps crashing and restarting:
```
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
invoiceninja_app_1 exited with code 2
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
app_1   | ls: cannot access '/var/www/app/docker-backup-public/logo/': No such file or directory
invoiceninja_app_1 exited with code 2
```

I already `mkdir /home/apps/invoiceninja/docker-backup-public` first (the error before that was that folder missing), and did `mkdir /home/apps/invoiceninja/docker-backup-public/logo`, but the error is still prevalent.
What is happening in the container, what business does it have with this folder and why is it trying to `ls` into it? Could you not do things like that without documenting it?
