### ISSUE TITLE
Impossible to find the app port entry

### ISSUE THREAD

**Issue by Hydrog3n** [invoiceninja/dockerfiles#81]
Hi, I try to use your image on my docker system with this docker-compose but nothing work to find the good port or have an real error

```
version: '2'

services:

  # Reverse Proxy
  nginx:
    image: xataz/reverse-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - invoice
    volumes:
      - /mnt/docker/nginx/ssl:/nginx/ssl
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker/nginx/custom_sites:/nginx/custom_sites
    environment:
      - EMAIL=contact@invoice.domain.tld
    networks:
      - proxy

  # Invoice Ninja
  invoice:
    image: invoiceninja/invoiceninja
    restart: always
    volumes:
      - /mnt/docker/invoiceninja/logo:/var/www/app/public/logo
      - /mnt/docker/invoiceninja/storage:/var/www/app/storage
    environment:
      - TRUSTED_PROXIES='10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      - APP_DEBUG=1
      - APP_ENV=production
      - APP_URL='https://invoice.invoice.domain.tld'
      - APP_KEY=mysecret
      - APP_CIPHER=AES-256-CBC
      - DB_USERNAME=invoice
      - DB_PASSWORD=xxxx
      - DB_HOST=db-invoice
      - DB_DATABASE=ninja
      - MAIL_HOST=mail.invoice.domain.tld
      - MAIL_USERNAME=contact@invoice.domain.tld
      - MAIL_PASSWORD=xxxxx
      - MAIL_DRIVER=smtp
      - MAIL_FROM_NAME="Hydrog3n"
      - MAIL_FROM_ADDRESS=contact@invoice.domain.tld
    labels:
      - reverse.frontend.domain=invoice.domain.tld
      - reverse.frontend.path=/
      - reverse.backend.port=80
      - reverse.frontend.ssl=enable
    networks:
      - proxy
      - db

  db-invoice:
    image: mariadb:10.1
    container_name: mariadb-invoice
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx}
      - MYSQL_DATABASE=invoice
      - MYSQL_USER=invoice
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /mnt/docker/mysql_invoiceninja/db:/var/lib/mysql
    networks:
      - db
```

Thank for the help.
