### ISSUE TITLE
Kubernetes?

### ISSUE THREAD

**Issue by spacepluk** [invoiceninja/dockerfiles#94]
Did anybody manage to get this running on Kubernetes?
Thanks

**Comment by spacepluk** [comment]
This setup is working for me for a very simple deployment:

````
kind: Service
apiVersion: v1
metadata:
  name: invoiceninja
  labels:
    app: invoiceninja
  annotations:
    external-dns.alpha.kubernetes.io/hostname: yourdomain
spec:
  selector:
    app: invoiceninja
  ports:
    - name: http
      port: 80
      targetPort: http
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: invoiceninja
  labels:
    app: invoiceninja
data:
  nginx.conf: |
    user www-data;

    events {
      worker_connections 768;
    }

    http {
        upstream backend {
            server 127.0.0.1:9000;
        }
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        gzip on;
        gzip_disable "msie6";

        server {
            listen      80 default;
            server_name _;

            root /var/www/app/public;

            index index.php;

            charset utf-8;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            location = /favicon.ico { access_log off; log_not_found off; }
            location = /robots.txt  { access_log off; log_not_found off; }

            sendfile off;

            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass backend;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_intercept_errors on;
                fastcgi_buffer_size 16k;
                fastcgi_buffers 4 16k;
            }

            location ~ /\.ht {
                deny all;
            }
        }
    }
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: invoiceninja
  labels:
    app: invoiceninja
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: invoiceninja
    spec:
      containers:
        - name: invoiceninja
          image: invoiceninja/invoiceninja
          ports:
            - name: backend
              containerPort: 9000
          env:
            - name: APP_ENV
              value: 'production'
            - name: APP_DEBUG
              value: '0'
            - name: APP_URL
              value: 'yourdomain'
            - name: APP_KEY
              value: 'S0meRandomStringSomeRandomString'
            - name: APP_CIPHER
              value: 'AES-256-CBC'
            - name: TRUSTED_PROXIES
              value: '10.0.0.0/8'
            - name: DB_TYPE
              value: 'mysql'
            - name: DB_USERNAME
              value: 'root'
            - name: DB_PASSWORD
              value: 'ninja'
            - name: DB_HOST
              value: '127.0.0.1'
            - name: DB_DATABASE
              value: 'ninja'
            - name: MAIL_HOST
              value: mailserver
            - name: MAIL_DRIVER
              value: smtp
            - name: MAIL_FROM_NAME
              value: 'InvoiceNinja'
            - name: MAIL_FROM_ADDRESS
              value: 'finance@yourdomain'
          volumeMounts:
            - name: invoiceninja-shared
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage
              subPath: storage
            - name: invoiceninja-storage
              mountPath: /var/www/app/public/logo
              subPath: logo
        - image: mysql:5
          name: mysql
          args: ['--default-authentication-plugin=mysql_native_password']
          env:
          - name: MYSQL_DATABASE
            value: 'ninja'
          - name: MYSQL_ROOT_PASSWORD
            value: 'ninja'
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - name: invoiceninja-storage
              mountPath: /var/lib/mysql
              subPath: mysql
        - image: nginx:1
          name: nginx
          ports:
          - name: http
            containerPort: 80
          volumeMounts:
            - name: invoiceninja-shared
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage
              subPath: storage
            - name: invoiceninja-storage
              mountPath: /var/www/app/public/logo
              subPath: logo
            - name: invoiceninja
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: invoiceninja-shared
          emptyDir: {}
        - name: invoiceninja
          emptyDir: {}
        - name: invoiceninja-storage
          emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invoiceninja
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: invoiceninja-tls
    hosts:
    - yourdomain
  rules:
  - host: yourdomain
    http:
      paths:
      - path: /
        backend:
          serviceName: invoiceninja
          servicePort: 80

**Comment by lalop** [comment]
hello @spacepluk 
thank you for sharing this.
Do you know how other project manage to add this in their repository ?

**Comment by botzill** [comment]
Hi. Thx @spacepluk for sharing this.

How about creating a helm chart with this? It will be super helpful and easy to install and test.

Thx

**Comment by spacepluk** [comment]
@lalop sorry I didn't see your message.  Most projects I've seen just drop the yaml files in a [deploy folder](https://github.com/kubernetes/ingress-nginx/tree/master/deploy).

@botzill that's probably a good idea but I've never used helm myself :)

**Comment by botzill** [comment]
@spacepluk I'm doing some tests now. Will see how this is going and if all is OK, we can deploy one here: https://github.com/helm/charts. Will be good to have a review from you. 

Thx.

**Comment by Antipov-Anton** [comment]
@botzill What about helm chart for invoiceNinja, you planned to realise? I just research is any chart already available.

**Comment by rouja** [comment]
Hi,

I just create a helm chart to deploy invoice-ninja on kubernetes. You can find it [here](https://github.com/rouja/invoice-chart). I discovered invoice-ninja few days ago so probably some features are not working. I need feedbacks to improve the chart. So if someone is interested, please feel free to create issues on the repo.

Thx.

**Comment by lalop** [comment]
Hello, I can't manage the kubernetes part of invoice ninja, but if some of you are okay for maintaining it we may add an official chart to this repos

**Comment by spacepluk** [comment]
Since this is still the first hit when you google _"invoiceninja kubernetes"_... I figured I would share my updated config that works with v5 and the alpine images.  I hope that helps somebody.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: invoiceninja
  labels:
    app: invoiceninja
  annotations:
    external-dns.alpha.kubernetes.io/access: public
spec:
  selector:
    app: invoiceninja
  ports:
    - name: http
      port: 80
      targetPort: http
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: invoiceninja-nginx-config
  labels:
    app: invoiceninja
data:
  nginx.conf: |
    user www-data;

    events {
      worker_connections 768;
    }

    http {
        upstream backend {
            server 127.0.0.1:9000;
        }
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        gzip on;
        gzip_disable "msie6";

        server {
            listen      80 default;
            server_name _;

            root /var/www/app/public;

            index index.php;

            charset utf-8;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            location = /favicon.ico { access_log off; log_not_found off; }
            location = /robots.txt  { access_log off; log_not_found off; }

            sendfile off;

            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass backend;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_intercept_errors on;
                fastcgi_param HTTPS 1;
                fastcgi_buffer_size 16k;
                fastcgi_buffers 4 16k;
            }

            location ~ /\.ht {
                deny all;
            }
        }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: invoiceninja
  labels:
    app: invoiceninja
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: invoiceninja
  template:
    metadata:
      labels:
        app: invoiceninja
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1500:82 /var/www/app/public /var/www/app/storage"]
        volumeMounts:
        - name: invoiceninja-shared
          mountPath: /var/www/app/public
        - name: invoiceninja-storage
          mountPath: /var/www/app/storage
          subPath: storage
        - name: invoiceninja-storage
          mountPath: /var/www/app/public/storage
          subPath: public-storage
      containers:
        - name: invoiceninja
          image: invoiceninja/invoiceninja:5.0.47
          ports:
            - name: backend
              containerPort: 9000
          env:
            - name: APP_ENV
              value: 'production'
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: 'https://invoice.yourdomain.com'
            - name: APP_KEY
              value: 'S0meR4nd0mStr1ngS0meR4nd0mStr1ng'
            - name: APP_CIPHER
              value: 'AES-256-CBC'
            - name: TRUSTED_PROXIES
              value: '*'
            - name: DB_TYPE
              value: 'mysql'
            - name: DB_STRICT
              value: 'false'
            - name: DB_HOST1
              value: '127.0.0.1'
            - name: DB_DATABASE1
              value: 'ninja'
            - name: DB_USERNAME1
              value: 'root'
            - name: DB_PASSWORD1
              value: 'ninja'
          volumeMounts:
            - name: invoiceninja-shared
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage
              subPath: storage
            - name: invoiceninja-storage
              mountPath: /var/www/app/public/storage
              subPath: public-storage
            - name: invoiceninja-storage
              mountPath: /mnt
        - image: mysql:5
          name: mysql
          args: ['--default-authentication-plugin=mysql_native_password']
          env:
          - name: MYSQL_DATABASE
            value: 'ninja'
          - name: MYSQL_ROOT_PASSWORD
            value: 'ninja'
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - name: invoiceninja-storage
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: invoiceninja-storage
              mountPath: /data
        - image: nginx:1
          name: nginx
          ports:
          - name: http
            containerPort: 80
          volumeMounts:
            - name: invoiceninja-shared
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage
              subPath: storage
            - name: invoiceninja-storage
              mountPath: /var/www/app/public/storage
              subPath: public-storage
            - name: invoiceninja-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: invoiceninja-shared
          emptyDir: {}
        - name: invoiceninja-nginx-config
          configMap:
            name: invoiceninja-nginx-config
        - name: invoiceninja-storage
          persistentVolumeClaim:
            claimName: invoiceninja-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invoiceninja
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - invoice.yourdomain.com
    secretName: invoiceninja-tls
  rules:
  - host: invoice.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: invoiceninja
            port:
              number: 80
```
