### ISSUE TITLE
Change location of persistent data storage

### ISSUE THREAD

**Issue by nordge1** [invoiceninja/dockerfiles#98]
Using the stock docker-compose.yml, is there a way to change the persistent data storage to be located a defined folder?  In other words is there a way to define the location of the Volumes at the top of the yml?

```
version: '3.6'

volumes:
  db:
  storage:
  logo:
  public:
```
